Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2020-03, with the labels that each got.

#36 b/149050012: Support HTTP protocols for remote backends
  examples/dynamic_routing/envoy_config.json
  examples/dynamic_routing/openapi_swagger.json
  examples/dynamic_routing/service_config_generated.json
  go.mod
  go.sum
  src/go/configgenerator/cluster_generator.go
  src/go/configinfo/service_info.go
  src/go/util/url_util.go
  src/go/util/url_util_test.go
  src/go/util/util.go
Labels: approved, enhancement, lgtm, size/L

#38 add a positive test for TLS between proxy and remote backend
  tests/integration_test/dynamic_routing_test/dynamic_routing_integration_test.go
Labels: approved, lgtm, size/M

#32 add TLS support for downstream
  docker/generic/start_proxy.py
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  src/go/bootstrap/static/bootstrap.go
  src/go/bootstrap/static/testdata/path_matcher/envoy_config.json
  src/go/configgenerator/cluster_generator.go
  src/go/configgenerator/cluster_generator_test.go
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/config_manager.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/flags/flags.go
  src/go/configmanager/testdata/fake_data_for_dynamic_routing.go
  src/go/options/configgenerator.go
  src/go/util/marshal.go
  src/go/util/transport_socket.go
  tests/endpoints/echo/client/client.go
  tests/env/components/ports.go
  tests/env/testdata/proxy.crt
  tests/env/testdata/proxy.key
  tests/env/testdata/server.crt
  tests/env/testdata/server.key
  tests/integration_test/transport_security_test/transport_security_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/XL

#39 Minor changes to fuzz targets
  src/envoy/http/backend_routing/BUILD
  tests/fuzz/corpus/iam_token_subscriber/invalid-header-values.prototxt
Labels: approved, lgtm, size/S

#40 b/150628278: include SA email in fetched iam id token
  src/envoy/token/BUILD
  src/envoy/token/iam_token_info.cc
  src/envoy/token/iam_token_info.h
  src/envoy/token/iam_token_info_test.cc
  src/envoy/token/iam_token_subscriber_fuzz_test.cc
  src/envoy/token/token_subscriber_factory_impl.h
  tests/integration_test/backend_auth_using_iam_test/backend_auth_using_iam_test.go
Labels: approved, lgtm, size/M

#37 b/149491061: Signal ready only when all tokens are successfully retried
  src/envoy/token/token_subscriber.cc
  src/envoy/token/token_subscriber_test.cc
  tests/env/components/mock_iam.go
  tests/env/components/ports.go
  tests/env/env.go
  tests/integration_test/backend_auth_using_iam_test/backend_auth_using_iam_test.go
  tests/integration_test/backend_auth_using_imds_test/backend_auth_using_imds_test.go
  tests/integration_test/iam_imds_data_path_test/iam_imds_data_path_test.go
Labels: approved, enhancement, lgtm, size/L

#42 Improve performance and coverage of fuzz tests for `TokenInfo`
  src/envoy/token/BUILD
  src/envoy/token/iam_token_info_fuzz_test.cc
  src/envoy/token/iam_token_subscriber_fuzz_test.cc
  src/envoy/token/imds_token_info_fuzz_test.cc
  src/envoy/token/token_subscriber_test.cc
  tests/fuzz/corpus/BUILD
  tests/fuzz/corpus/iam_token_info/valid-access-token-simple.prototxt
  tests/fuzz/corpus/iam_token_info/valid-id-token-simple.prototxt
  tests/fuzz/corpus/iam_token_info/valid-with-delegates.prototxt
  tests/fuzz/corpus/iam_token_info/valid-with-scopes.prototxt
  tests/fuzz/corpus/iam_token_subscriber/invalid-header-values.prototxt
  tests/fuzz/corpus/iam_token_subscriber/invalid-throws-exception-leak.prototxt
  tests/fuzz/corpus/iam_token_subscriber/valid-multiple-headers.prototxt
  tests/fuzz/corpus/iam_token_subscriber/valid-simple-bad-body.prototxt
  tests/fuzz/corpus/iam_token_subscriber/valid-simple-bad-status.prototxt
  tests/fuzz/corpus/iam_token_subscriber/valid-simple.prototxt
  tests/fuzz/corpus/imds_token_info/valid-access-token-simple.prototxt
  tests/fuzz/corpus/imds_token_info/valid-id-token-simple.prototxt
  tests/fuzz/structured_inputs/BUILD
  tests/fuzz/structured_inputs/iam_token_info.proto
  tests/fuzz/structured_inputs/iam_token_subscriber.proto
  tests/fuzz/structured_inputs/imds_token_info.proto
Labels: approved, lgtm, size/L

#41 cleanup duplicated normalizeJson
  src/go/bootstrap/ads/bootstrap_test.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/config_manager_test.go
  src/go/util/httptest_util.go
  tests/integration_test/backend_auth_disable_auth_test/backend_auth_disable_auth_test.go
  tests/integration_test/backend_auth_using_iam_test/backend_auth_using_iam_test.go
  tests/integration_test/backend_auth_using_imds_test/backend_auth_using_imds_test.go
  tests/integration_test/dynamic_routing_test/dynamic_routing_integration_test.go
  tests/integration_test/iam_imds_data_path_test/iam_imds_data_path_test.go
  tests/utils/util.go
Labels: approved, size/L

#43 add backward compability for ssl_port
  docker/generic/start_proxy.py
  src/go/util/transport_socket.go
  src/go/util/transport_socket_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/L

#48 Update CHANGELOG and VERSION for 2.6.0 release
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#47 Update version number to 2.7.0.
  VERSION
Labels: approved, lgtm, size/XS

#50 update script after migrating to github
  scripts/all-utilities.sh
  scripts/release/release-new-branch.sh
  scripts/release/release-publish.sh
  scripts/release/release-tag-git.sh
Labels: approved, lgtm, size/S

#49 Add script to check unit and fuzz target coverage for C++ code
  .gitignore
  src/envoy/http/path_matcher/filter_test.cc
  src/envoy/http/service_control/filter_test.cc
  tests/fuzz/README.md
  third_party/tools/coverage/README.md
  third_party/tools/coverage/cpp_fuzz.sh
  third_party/tools/coverage/cpp_unit.sh
  third_party/tools/coverage/gen_build.sh
  third_party/tools/coverage/gen_coverage.sh
Labels: approved, lgtm, size/L

#51 Update envoy to 2020-03-03
  WORKSPACE
  src/envoy/http/backend_auth/filter.cc
  src/envoy/http/backend_auth/filter.h
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/http/backend_routing/filter.cc
  src/envoy/http/backend_routing/filter.h
  src/envoy/http/backend_routing/filter_fuzz_test.cc
  src/envoy/http/backend_routing/filter_test.cc
  src/envoy/http/path_matcher/filter.cc
  src/envoy/http/path_matcher/filter.h
  src/envoy/http/path_matcher/filter_test.cc
  src/envoy/http/service_control/filter.cc
  src/envoy/http/service_control/filter.h
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/handler_utils.cc
  src/envoy/http/service_control/handler_utils.h
  src/envoy/http/service_control/http_call.cc
  src/envoy/http/service_control/http_call_test.cc
  src/envoy/http/service_control/mocks.h
  src/envoy/token/iam_token_info.cc
  src/envoy/token/iam_token_info.h
  src/envoy/token/iam_token_info_test.cc
  src/envoy/token/imds_token_info.cc
  src/envoy/token/imds_token_info.h
  src/envoy/token/imds_token_info_test.cc
  src/envoy/token/mocks.h
  src/envoy/token/token_info.h
  src/envoy/token/token_subscriber.cc
  src/envoy/token/token_subscriber.h
  src/envoy/token/token_subscriber_test.cc
Labels: approved, lgtm, size/XL

#53 Add fuzz test for gen auth token
  src/api_proxy/auth/BUILD
  src/api_proxy/auth/auth_token_fuzz_test.cc
  tests/fuzz/corpus/BUILD
  tests/fuzz/corpus/auth_token/invalid-simple.prototxt
  tests/fuzz/corpus/auth_token/valid-realistic.prototxt
  tests/fuzz/structured_inputs/BUILD
  tests/fuzz/structured_inputs/auth_token.proto
Labels: approved, lgtm, size/M

#45 b/139312546: Add override for platform.
  src/go/gcsrunner/transform_config.go
  src/go/gcsrunner/transform_config_test.go
Labels: approved, lgtm, size/M

#44 b/149484856,b/150725812: Support custom jwt locations
  api/envoy/http/service_control/requirement.proto
  examples/grpc_dynamic_routing/envoy_config.json
  go.mod
  go.sum
  src/envoy/http/service_control/config_parser.h
  src/envoy/http/service_control/handler_utils.cc
  src/envoy/http/service_control/handler_utils.h
  src/envoy/http/service_control/handler_utils_test.cc
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/config_manager_test.go
  src/go/util/util.go
  tests/endpoints/echo/client/client.go
  tests/env/components/mock_jwt_provider.go
  tests/env/components/ports.go
  tests/env/testdata/fake_jwt.go
  tests/integration_test/jwt_auth_test/jwt_auth_integration_test.go
  tests/integration_test/jwt_locations_test/jwt_locations_test.go
  tests/integration_test/service_control_api_key_location_test/service_control_apikey_location_test.go
Labels: approved, lgtm, size/XXL

#54 Refactory: user request_info.current_time
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/service_control/request_builder.h
  src/api_proxy/service_control/request_builder_test.cc
  src/api_proxy/service_control/request_info.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl.h
Labels: approved, lgtm, size/M

#55 Add rudimentary fuzz test for service control filter
  api/envoy/http/service_control/BUILD
  src/api_proxy/auth/auth_token_fuzz_test.cc
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/filter_fuzz_test.cc
  src/envoy/http/service_control/http_call.cc
  tests/fuzz/corpus/BUILD
  tests/fuzz/corpus/service_control_filter/all-metrics.prototxt
  tests/fuzz/corpus/service_control_filter/bad-check.prototxt
  tests/fuzz/corpus/service_control_filter/bad-quota.prototxt
  tests/fuzz/corpus/service_control_filter/sc-retries.prototxt
  tests/fuzz/corpus/service_control_filter/valid-request-complex.prototxt
  tests/fuzz/corpus/service_control_filter/valid-request.prototxt
  tests/fuzz/structured_inputs/BUILD
  tests/fuzz/structured_inputs/backend_routing_filter.proto
  tests/fuzz/structured_inputs/service_control_filter.proto
Labels: approved, lgtm, size/XXL

#57 b/140446546: add PrintOptions for transcoder
  Makefile
  docker/generic/start_proxy.py
  examples/grpc_dynamic_routing/envoy_config.json
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  tests/endpoints/bookstore_grpc/proto/api_descriptor.pb
  tests/endpoints/bookstore_grpc/proto/v1/bookstore.pb.go
  tests/endpoints/bookstore_grpc/proto/v1/bookstore.proto
  tests/endpoints/bookstore_grpc/proto/v2/bookstore_v2.pb.go
  tests/env/components/ports.go
  tests/env/env.go
  tests/integration_test/transcoding_bindings_test/transcoding_bindings_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/XL

#60 use envoy timeSource in service control filter
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/filter.cc
  src/envoy/http/service_control/filter_config.h
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/mocks.h
Labels: approved, lgtm, size/L

#61 b/151105334: remove useless default option settings
  src/go/options/common.go
  src/go/options/configgenerator.go
Labels: approved, lgtm, size/M

#58 add ssl_minimum_protocol and ssl_maximum_protocol for downstream
  docker/generic/start_proxy.py
  src/go/configgenerator/listener_generator.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  src/go/util/transport_socket.go
  src/go/util/transport_socket_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, size/L

#62 Use new style MOCK_METHOD for service_control mocks
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/mocks.h
Labels: approved, lgtm, size/L

#63 Validate urls in fuzz tests
  src/envoy/token/iam_token_info_fuzz_test.cc
  src/envoy/token/imds_token_info_fuzz_test.cc
  tests/fuzz/corpus/iam_token_info/invalid-url.prototxt
  tests/fuzz/corpus/imds_token_info/invalid-url.prototxt
  tests/fuzz/corpus/imds_token_info/valid-url.prototxt
  tests/fuzz/structured_inputs/iam_token_info.proto
  tests/fuzz/structured_inputs/imds_token_info.proto
Labels: approved, lgtm, size/S

#56 Add script to upload publicly-viewable C++ unit test coverage data
  docker/Dockerfile-prow-env
  prow/gcpproxy-coverage.sh
  third_party/tools/coverage/cpp_unit.sh
  third_party/tools/coverage/gen_build.sh
  third_party/tools/coverage/gen_coverage.sh
Labels: approved, lgtm, size/M

#65 Use choices in add_argument for start_proxy flags' allowed values
  docker/generic/start_proxy.py
Labels: approved, lgtm, size/S

#64 Add unit and integration test for HTTP/2 backends
  src/go/configinfo/service_info_test.go
  tests/endpoints/echo/server/app.go
  tests/env/components/echo_http_server.go
  tests/env/components/ports.go
  tests/env/env.go
  tests/integration_test/backend_auth_disable_auth_test.go
  tests/integration_test/backend_auth_using_iam_test.go
  tests/integration_test/backend_auth_using_imds_test.go
  tests/integration_test/backend_protocol_test.go
Labels: approved, lgtm, size/L

#66 Add badges for oss-fuzz and coverage reports
  README.md
Labels: approved, lgtm, size/XS

#69 Validate logged header format in service control config
  api/envoy/http/service_control/config.proto
  tests/fuzz/corpus/service_control_filter/crash-log-request-headers.prototxt
Labels: approved, lgtm, size/S

#72 Handle invalid service account files when generating tokens
  src/envoy/token/sa_token_generator.cc
  src/envoy/token/sa_token_generator.h
  src/envoy/token/sa_token_generator_test.cc
  src/envoy/token/token_subscriber_factory_impl.h
  tests/fuzz/corpus/service_control_filter/crash-sa-token-generator-null-token.prototxt
Labels: approved, lgtm, oss-fuzz-bug-fix, size/L

#71 Handle null pointer for running envoy in a named pipe
  api/envoy/http/service_control/config.proto
  src/envoy/http/service_control/handler_impl.cc
  tests/fuzz/corpus/service_control_filter/crash-downstream-address-pipe.prototxt
Labels: approved, lgtm, oss-fuzz-bug-fix, size/M

#70 Update envoy to 2020-03-12
  WORKSPACE
  src/envoy/http/service_control/handler_utils.cc
  src/envoy/http/service_control/handler_utils.h
  src/envoy/http/service_control/handler_utils_test.cc
Labels: approved, lgtm, size/S

#73 Validate URIs in envoy config
  api/envoy/http/backend_routing/config.proto
  api/envoy/http/common/base.proto
  src/envoy/http/service_control/handler_utils_test.cc
  src/envoy/token/iam_token_info_fuzz_test.cc
  src/envoy/token/imds_token_info_fuzz_test.cc
  tests/fuzz/corpus/service_control_filter/crash-bad-service-control-uri.prototxt
  tests/fuzz/structured_inputs/iam_token_info.proto
  tests/fuzz/structured_inputs/imds_token_info.proto
Labels: approved, lgtm, oss-fuzz-bug-fix, size/M

#74 Catch EnvoyException when fuzzing stream info
  src/envoy/http/service_control/filter_fuzz_test.cc
  tests/fuzz/corpus/service_control_filter/invalid-network-address.prototxt
Labels: approved, lgtm, oss-fuzz-bug-fix, size/M

#75 Treat status code in report as an unsigned int
  src/api_proxy/service_control/request_info.h
  tests/fuzz/corpus/service_control_filter/crash-response-code-overflow.prototxt
Labels: approved, lgtm, oss-fuzz-bug-fix, size/L

#77 Support strict transport security
  docker/generic/start_proxy.py
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  src/go/util/util.go
  tests/endpoints/echo/client/client.go
  tests/integration_test/transport_security_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/L

#79 b/150729554: enable ignoredQueryParameters and ignoredUnknownQueryPar…
  docker/generic/start_proxy.py
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  tests/env/components/ports.go
  tests/integration_test/transcoding_bindings_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/L

#76 b/151274198: refactor service_config_fetcher
  src/go/configmanager/config_manager.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/service_config_fetcher.go
  src/go/serviceconfig/service_config_fetcher.go
  src/go/serviceconfig/service_config_fetcher_test.go
  src/go/util/url_util.go
  tests/env/env.go
  tests/env/testdata/fake_echo_service_config.go
  tests/env/testdata/fake_echo_service_config_for_dynamic_routing.go
  tests/env/testdata/fake_grpc_bookstore_service_config.go
  tests/env/testdata/fake_grpc_echo_service_config.go
  tests/env/testdata/fake_grpc_echo_service_config_for_dynamic_routing.go
  tests/env/testdata/fake_grpc_interop_service_config.go
  tests/integration_test/managed_service_config_test.go
Labels: approved, size/XL

#80 Validate ApiKeyLocations
  api/envoy/http/service_control/requirement.proto
  tests/fuzz/corpus/service_control_filter/crash-api-key-header.prototxt
Labels: approved, lgtm, oss-fuzz-bug-fix, size/L

#81 Align `--disable_cloud_trace_auto_sampling` with ESPv1
  docker/generic/start_proxy.py
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/M

#82 b/151344434: Suppress envoy debug headers when `--enable_debug=false`
  docker/generic/start_proxy.py
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  src/go/bootstrap/static/testdata/path_matcher/envoy_config.json
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/flags/flags.go
  src/go/configmanager/testdata/fake_data_for_dynamic_routing.go
  src/go/options/configgenerator.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/M

#84 Use `EMPTY_STRING` envoy constant
  api/envoy/http/service_control/requirement.proto
  src/envoy/http/backend_auth/BUILD
  src/envoy/http/backend_auth/config_parser_impl.h
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/http/backend_routing/BUILD
  src/envoy/http/backend_routing/filter_test.cc
  src/envoy/http/path_matcher/BUILD
  src/envoy/http/path_matcher/filter_config.cc
  src/envoy/http/path_matcher/filter_config_test.cc
  src/envoy/http/path_matcher/filter_test.cc
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/handler_utils_test.cc
  src/envoy/http/service_control/http_call.cc
  src/envoy/token/BUILD
  src/envoy/token/iam_token_info.cc
  src/envoy/token/iam_token_info_test.cc
  src/envoy/utils/BUILD
  src/envoy/utils/filter_state_utils.cc
  src/envoy/utils/filter_state_utils_test.cc
  src/envoy/utils/http_header_utils.cc
Labels: approved, lgtm, security-review, size/L

#86 Ensure access/identity token from IMDS/IAM is a valid HTTP header value
  src/envoy/token/token_subscriber.cc
  src/envoy/token/token_subscriber_test.cc
  tests/fuzz/corpus/iam_token_info/invalid-imds-access-token.prototxt
  tests/fuzz/structured_inputs/iam_token_info.proto
Labels: approved, lgtm, oss-fuzz-bug-fix, size/M

#85 Add missing tests and validation for Path Matcher filter
  api/envoy/http/common/base.proto
  src/api_proxy/path_matcher/variable_binding_utils_test.cc
  src/envoy/http/path_matcher/filter_config.cc
  src/envoy/http/path_matcher/filter_config_test.cc
  src/envoy/http/path_matcher/filter_test.cc
Labels: approved, lgtm, security-review, size/M

#87 Ignore invalid http header characters in backend routing filter fuzz test
  src/envoy/http/backend_routing/filter_fuzz_test.cc
  tests/fuzz/corpus/backend_routing_filter/crash-invalid-binding-query-params.prototxt
  tests/fuzz/structured_inputs/backend_routing_filter.proto
Labels: approved, lgtm, oss-fuzz-bug-fix, size/M

#88 Switch /src/api_proxy to envoy_build_system
  src/api_proxy/path_matcher/BUILD
  src/api_proxy/service_control/BUILD
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/utils/BUILD
Labels: approved, lgtm, size/M

#83 b/151274198: fetch config id from servicecontrol
  go.sum
  src/go/configmanager/config_manager.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  src/go/serviceconfig/rollout_id_change_detector.go
  src/go/serviceconfig/rollout_id_change_fetcher_test.go
  src/go/serviceconfig/service_config_fetcher.go
  src/go/serviceconfig/service_config_fetcher_test.go
  src/go/util/marshal.go
  src/go/util/marshal_test.go
  src/go/util/request.go
  src/go/util/request_test.go
  src/go/util/testdata/fake_service_account.json
  src/go/util/token_generator.go
  src/go/util/token_generator_test.go
  src/go/util/url_util.go
  src/go/util/url_util_test.go
  src/go/util/util.go
  tests/env/components/mock_service_control.go
  tests/env/components/mock_service_control_test.go
  tests/env/components/mock_service_management.go
  tests/env/components/mock_service_management_test.go
  tests/env/env.go
  tests/env/platform/files.go
  tests/integration_test/managed_service_config_test.go
Labels: approved, lgtm, size/XXL

#90 Add X-Forwarded-Authorization header
  src/envoy/http/backend_auth/filter.cc
  src/envoy/http/backend_auth/filter_test.cc
  tests/endpoints/echo/server/app.go
  tests/env/platform/files.go
  tests/integration_test/backend_auth_disable_auth_test.go
Labels: approved, lgtm, size/M

#91 Update version number to 2.8.0.
  VERSION
Labels: approved, lgtm, size/XS

#93 Add changelog for 2.7.0
  CHANGELOG.md
Labels: approved, lgtm, size/S

#96 Add fuzz test for Path Matcher filter
  api/envoy/http/path_matcher/BUILD
  src/envoy/http/path_matcher/BUILD
  src/envoy/http/path_matcher/README.md
  src/envoy/http/path_matcher/filter.cc
  src/envoy/http/path_matcher/filter_fuzz_test.cc
  src/envoy/http/path_matcher/filter_test.cc
  tests/fuzz/corpus/BUILD
  tests/fuzz/corpus/path_matcher_filter/invalid-missing-headers.prototxt
  tests/fuzz/corpus/path_matcher_filter/valid-extract-path-params.prototxt
  tests/fuzz/corpus/path_matcher_filter/valid-method-override.prototxt
  tests/fuzz/corpus/path_matcher_filter/valid-simple.prototxt
  tests/fuzz/structured_inputs/BUILD
  tests/fuzz/structured_inputs/path_matcher_filter.proto
Labels: approved, lgtm, security-review, size/L

#97 b/149050012: Run e2e tests with HTTP/2
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: approved, lgtm, size/XS

#95 TLS support for grpcs backend
  docker/generic/start_proxy.py
  tests/endpoints/bookstore_grpc/server/server.go
  tests/env/components/config_manager.go
  tests/env/components/ports.go
  tests/env/env.go
  tests/env/platform/backend.go
  tests/env/testdata/fake_grpc_bookstore_service_config_dynamic_routing.go
  tests/env/testdata/fake_service_config_map.go
  tests/integration_test/dynamic_routing_integration_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/L

#98 b/149484856: e2e test x-google-jwt-locations
  tests/e2e/client/apiproxy_bookstore_test.py
  tests/e2e/scripts/prow-utilities.sh
  tests/endpoints/bookstore/bookstore_swagger_template.json
Labels: approved, lgtm, size/M

#99 b/152686575: update to latest filter names
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  src/envoy/README.md
  src/envoy/http/service_control/testdata/envoy.yaml
  src/go/bootstrap/static/testdata/path_matcher/envoy_config.json
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/testdata/fake_data_for_dynamic_routing.go
  src/go/gcsrunner/transform_config_test.go
  src/go/util/util.go
Labels: approved, lgtm, size/L

#100 add integration test for gRPCs mTLS
  tests/endpoints/bookstore_grpc/server/server.go
  tests/env/env.go
  tests/integration_test/dynamic_routing_integration_test.go
Labels: approved, lgtm, size/M

#101 b/149484856: add additional jwtLocation e2e tests
  tests/e2e/client/apiproxy_bookstore_test.py
Labels: approved, lgtm, size/S

#94 b/152394779: put gcsrunner in official release images
  scripts/all-utilities.sh
  scripts/release/release-publish.sh
  scripts/release/release-show.sh
  scripts/release/release-stable.sh
Labels: approved, lgtm, size/M
