Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2020-07, with the labels that each got.

#216 Create FilterStats in client_cache
  src/envoy/http/service_control/client_cache.cc
  src/envoy/http/service_control/client_cache.h
  src/envoy/http/service_control/client_cache_test.cc
  src/envoy/http/service_control/filter_config.h
  src/envoy/http/service_control/filter_stats.h
  src/envoy/http/service_control/filter_stats_test.cc
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/handler_utils_test.cc
  src/envoy/http/service_control/service_control_call_impl.cc
  src/envoy/http/service_control/service_control_call_impl.h
Labels: approved, lgtm, size/L

#217 Update envoy to 7/6/2020
  WORKSPACE
  src/envoy/http/backend_auth/filter.cc
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/http/service_control/http_call.cc
  src/envoy/http/service_control/http_call_test.cc
  src/envoy/token/iam_token_info_test.cc
  src/envoy/token/token_subscriber.h
  tests/e2e/scripts/cloud-run/deploy.sh
  tests/endpoints/bookstore_grpc/client/client.go
Labels: approved, lgtm, size/M

#219 Update version number to 2.14.0.
  VERSION
Labels: approved, lgtm, size/XS

#222 Fix coverage URL
  README.md
Labels: approved, documentation, lgtm, size/XS

#223 b/152977807: rewrite unit test to use table driven format
  src/go/util/marshal_test.go
Labels: approved, lgtm, size/M

#224 b/152977807: rewrite rollout_id_change_fetcher_test.go to table driven
  src/go/serviceconfig/rollout_id_change_fetcher_test.go
Labels: approved, lgtm, size/M

#225 Format examples with script, redeploy examples in `cloudesf-testing`
  Makefile
  examples/README.md
  examples/auth/envoy_config.json
  examples/auth/openapi_swagger.json
  examples/auth/service_config_generated.json
  examples/dynamic_routing/envoy_config.json
  examples/dynamic_routing/openapi_swagger.json
  examples/dynamic_routing/service_config_generated.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/grpc-test.yaml
  examples/grpc_dynamic_routing/service_config_generated.json
  examples/service_control/envoy_config.json
  examples/service_control/openapi_swagger.json
  examples/service_control/service_config_generated.json
  examples/testdata/README.md
  examples/testdata/path_matcher/envoy_config.json
  examples/testdata/path_matcher/openapi_swagger.json
  examples/testdata/path_matcher/service_config_generated.json
  scripts/format-examples.sh
Labels: approved, documentation, lgtm, size/XXL

#218 b/158262661: Move snake to json segment mapping to per-operation instead of global
  api/envoy/v6/http/path_matcher/config.proto
  examples/testdata/README.md
  examples/testdata/path_matcher/envoy_config.json
  examples/testdata/path_matcher/openapi_swagger.json
  examples/testdata/path_matcher/service_config_generated.json
  src/api_proxy/path_matcher/BUILD
  src/api_proxy/path_matcher/variable_binding_utils.cc
  src/api_proxy/path_matcher/variable_binding_utils.h
  src/api_proxy/path_matcher/variable_binding_utils_test.cc
  src/envoy/http/path_matcher/filter.cc
  src/envoy/http/path_matcher/filter_config.cc
  src/envoy/http/path_matcher/filter_config.h
  src/envoy/http/path_matcher/filter_config_test.cc
  src/envoy/http/path_matcher/filter_test.cc
  src/go/bootstrap/static/bootstrap_test.go
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/serviceconfig/rollout_id_change_fetcher_test.go
  src/go/util/httptest_util.go
  src/go/util/util.go
  tests/env/testdata/fake_echo_service_config_for_dynamic_routing.go
  tests/env/testdata/service_config_for_fixed_dynamic_routing.json
  tests/fuzz/corpus/path_matcher_filter/invalid-missing-headers.prototxt
  tests/fuzz/corpus/path_matcher_filter/valid-extract-path-params.prototxt
Labels: approved, breaking-api-change, bug, lgtm, size/XL

#227 b/161168963: Include Access Loggers in JSON Any resolver
  src/go/util/marshal.go
  src/go/util/marshal_test.go
Labels: approved, lgtm, size/M

#230 b/161168963: Add StatsConfig and StatsSink to Resolver
  src/go/util/marshal.go
  src/go/util/marshal_test.go
Labels: approved, lgtm, size/S

#232 Update version number to 2.15.0 and CHANGELOG
  CHANGELOG.md
  VERSION
Labels: approved, lgtm, size/XS

#234 replace typepb for genproto
  src/go/configinfo/service_info.go
Labels: approved, lgtm, size/XS

#233 b/161200191: add api_key in filter_state for access logging
  src/envoy/http/backend_auth/filter.cc
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/http/backend_routing/filter.cc
  src/envoy/http/backend_routing/filter_fuzz_test.cc
  src/envoy/http/backend_routing/filter_test.cc
  src/envoy/http/path_matcher/filter.cc
  src/envoy/http/path_matcher/filter_fuzz_test.cc
  src/envoy/http/path_matcher/filter_test.cc
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/client_cache_test.cc
  src/envoy/http/service_control/filter.cc
  src/envoy/http/service_control/filter_fuzz_test.cc
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/mocks.h
  src/envoy/utils/filter_state_utils.h
  tests/integration_test/access_log_test.go
Labels: approved, lgtm, size/L

#229 b/161293641: Support ESP versions in `gcloud_build_image`
  docker/serverless/gcloud_build_image
  prow/e2e-gcloud-build-image.sh
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: approved, lgtm, size/L

#235 b/161168963: Add statsd to Envoy build
  envoy_build_config/extensions_build_config.bzl
Labels: approved, lgtm, size/XS

#236 b/161827325: add original_path in FilterState for access log
  src/envoy/http/service_control/filter.cc
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/mocks.h
  src/envoy/utils/filter_state_utils.h
  tests/integration_test/access_log_test.go
Labels: approved, size/L

#240 Fail `gcloud_build_image` early on error
  docker/serverless/gcloud_build_image
Labels: approved, lgtm, size/XS

#242 Revert "b/161827325: add original_path in FilterState for access log
  src/envoy/http/service_control/filter.cc
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/mocks.h
  src/envoy/utils/filter_state_utils.h
  tests/integration_test/access_log_test.go
Labels: approved, lgtm, size/L

#246 Fix `glcoud_build_image`
  docker/serverless/gcloud_build_image
Labels: approved, bug, lgtm, size/S

#241 b/161827325: set `x-envoy-original-path` in backend routing filter
  src/envoy/http/backend_routing/filter.cc
  src/envoy/http/backend_routing/filter_test.cc
  src/envoy/http/path_matcher/filter.cc
  src/envoy/http/service_control/handler_impl_test.cc
  tests/integration_test/access_log_test.go
Labels: approved, lgtm, size/L

#247 Support tracing in http bookstore backend
  Makefile
  tests/e2e/scripts/cloud-run/deploy.sh
  tests/e2e/testdata/bookstore/gke/http-bookstore.yaml.template
  tests/endpoints/bookstore/bookstore.Dockerfile
  tests/endpoints/bookstore/http_bookstore.js
  tests/endpoints/bookstore/package-lock.json
  tests/endpoints/bookstore/package.json
Labels: approved, lgtm, size/XXL

#250 b/161200191,b/162231154: Add api_method in service control filter
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/utils/filter_state_utils.h
  tests/integration_test/access_log_test.go
Labels: approved, lgtm, size/S
