Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2020-05, with the labels that each got.

#144 Destruct invalid json keys in grpc auth lib
  src/api_proxy/auth/auth_token.cc
Labels: approved, lgtm, size/XS

#145 [Cleanup] Minor lint changes to unblock google3 copybara
  api/envoy/http/backend_auth/BUILD
  api/envoy/http/backend_routing/BUILD
  api/envoy/http/common/BUILD
  api/envoy/http/path_matcher/BUILD
  api/envoy/http/service_control/BUILD
  src/go/configinfo/service_info_test.go
  src/go/configmanager/config_manager_test.go
Labels: approved, lgtm, size/M

#147 make cluster for cloud run(anthos) test use lates version
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: approved, lgtm, size/XS

#146 b/155213423: add latency in ServiceControl statistics
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/filter.cc
  src/envoy/http/service_control/filter_stats.h
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/handler_utils.cc
  src/envoy/http/service_control/handler_utils.h
  src/envoy/http/service_control/handler_utils_test.cc
  src/envoy/http/service_control/mocks.h
  tests/endpoints/echo/client/client.go
  tests/env/components/ports.go
  tests/integration_test/statistics_test.go
  tests/utils/http.go
  tests/utils/stats.go
Labels: approved, size/L

#152 Fix network fail open for Unavailable CheckResponse errors
  src/api_proxy/service_control/check_response_test.cc
  src/api_proxy/service_control/request_builder.cc
  src/envoy/http/service_control/client_cache.cc
  tests/env/components/ports.go
  tests/integration_test/service_control_check_network_fail_test.go
Labels: approved, lgtm, size/L

#153 Sync check response proto
  src/api_proxy/service_control/check_response_test.cc
  src/api_proxy/service_control/request_builder.cc
Labels: approved, size/M

#151 b/155212712: add statistical counter for check/allocateQuota/report call status
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/client_cache.cc
  src/envoy/http/service_control/client_cache.h
  src/envoy/http/service_control/filter.cc
  src/envoy/http/service_control/filter_config.h
  src/envoy/http/service_control/filter_stats.cc
  src/envoy/http/service_control/filter_stats.h
  src/envoy/http/service_control/filter_stats_test.cc
  src/envoy/http/service_control/handler_utils.cc
  src/envoy/http/service_control/service_control_call_impl.cc
  src/envoy/http/service_control/service_control_call_impl.h
  tests/env/components/mock_service_control.go
  tests/env/components/ports.go
  tests/integration_test/statistics_test.go
Labels: approved, lgtm, size/XL

#154 Assert path matcher query params are valid in fuzz test
  src/api_proxy/service_control/check_response_test.cc
  src/envoy/http/path_matcher/BUILD
  src/envoy/http/path_matcher/filter_fuzz_test.cc
Labels: approved, lgtm, security-review, size/S

#157 Fix nil in listener generator test
  src/go/configgenerator/listener_generator_test.go
Labels: approved, lgtm, size/S

#156 b/155209585 #2: Implement `denied_consumer_blocked` and `denied_consumer_error` stats
  src/api_proxy/service_control/check_response_test.cc
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/service_control/request_info.h
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/client_cache.cc
  src/envoy/http/service_control/client_cache.h
  src/envoy/http/service_control/client_cache_test.cc
  src/envoy/http/service_control/filter_stats.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl_test.cc
Labels: approved, lgtm, size/L

#159 Update version number to 2.11.0.
  VERSION
Labels: approved, lgtm, size/XS

#160 Update CHANGELOG for v2.10.0 release
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#158 Variety of fixes for file-based tests in google3
  examples/BUILD
  examples/README.md
  examples/testdata/README.md
  examples/testdata/path_matcher/envoy_config.json
  examples/testdata/path_matcher/openapi_swagger.json
  examples/testdata/path_matcher/service_config_generated.json
  src/envoy/http/path_matcher/README.md
  src/go/configmanager/config_manager_test.go
  src/go/util/marshal_test.go
  src/go/util/testdata/fake_service_account.json
  src/go/util/token_generator.go
  src/go/util/token_generator_test.go
  tests/env/platform/files.go
  tests/env/testdata/BUILD
  tests/env/testdata/roots.pem
  tests/env/testdata/service_config_for_fixed_dynamic_routing.json
Labels: approved, size/XXL

#161 Improve readability/validation of backend routing config and filter
  api/envoy/http/backend_routing/config.proto
  examples/dynamic_routing/envoy_config.json
  src/envoy/http/backend_routing/BUILD
  src/envoy/http/backend_routing/filter.cc
  src/envoy/http/backend_routing/filter.h
  src/envoy/http/backend_routing/filter_config.h
  src/envoy/http/backend_routing/filter_test.cc
  src/envoy/http/service_control/BUILD
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/testdata/fake_data_for_dynamic_routing.go
Labels: approved, breaking-api-change, lgtm, security-review, size/L

#163 b/155209585 #3: Implement `denied_consumer_quota` and `denied_producer_error`
  src/api_proxy/service_control/check_response_test.cc
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/service_control/request_builder.h
  src/api_proxy/service_control/request_info.h
  src/envoy/http/service_control/README.md
  src/envoy/http/service_control/client_cache.cc
  src/envoy/http/service_control/client_cache.h
  src/envoy/http/service_control/client_cache_test.cc
  src/envoy/http/service_control/filter_stats.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl_test.cc
Labels: approved, lgtm, size/L

#164 Handle errors and test stats in Backend Routing
  src/envoy/http/backend_routing/BUILD
  src/envoy/http/backend_routing/README.md
  src/envoy/http/backend_routing/filter.cc
  src/envoy/http/backend_routing/filter.h
  src/envoy/http/backend_routing/filter_config.h
  src/envoy/http/backend_routing/filter_test.cc
Labels: approved, lgtm, security-review, size/L

#165 Update envoy to 2020-05-26
  .bazelrc
  WORKSPACE
  docker/Dockerfile-prow-env
  prow/gcpproxy-coverage.sh
  src/envoy/http/backend_routing/BUILD
  src/envoy/http/backend_routing/filter_fuzz_test.cc
  src/envoy/http/path_matcher/BUILD
  src/envoy/http/path_matcher/filter_fuzz_test.cc
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/filter_fuzz_test.cc
  src/envoy/http/service_control/handler_impl_test.cc
  tests/env/components/dns_resolver.go
  tests/fuzz/corpus/backend_routing_filter/crash-invalid-binding-query-params.prototxt
  tests/fuzz/corpus/backend_routing_filter/missing-path.prototxt
  tests/fuzz/corpus/backend_routing_filter/valid-append-query-params.prototxt
  tests/fuzz/corpus/backend_routing_filter/valid-append-simple.prototxt
  tests/fuzz/corpus/backend_routing_filter/valid-const-query-params.prototxt
  tests/fuzz/corpus/backend_routing_filter/valid-const-simple.prototxt
  tests/fuzz/corpus/service_control_filter/all-metrics.prototxt
  tests/fuzz/corpus/service_control_filter/bad-check.prototxt
  tests/fuzz/corpus/service_control_filter/bad-quota.prototxt
  tests/fuzz/corpus/service_control_filter/crash-api-key-header.prototxt
  tests/fuzz/corpus/service_control_filter/crash-bad-service-control-uri.prototxt
  tests/fuzz/corpus/service_control_filter/crash-response-code-overflow.prototxt
  tests/fuzz/corpus/service_control_filter/crash-sa-token-generator-null-token.prototxt
  tests/fuzz/corpus/service_control_filter/sc-retries.prototxt
  tests/fuzz/corpus/service_control_filter/valid-request-complex.prototxt
  tests/fuzz/corpus/service_control_filter/valid-request.prototxt
  tests/fuzz/structured_inputs/backend_routing_filter.proto
  tests/integration_test/dns_resolver_test.go
  tests/integration_test/managed_service_config_test.go
  third_party/tools/coverage/cpp_unit.sh
  third_party/tools/coverage/gen_build.sh
Labels: approved, size/XL
