Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2020-02, with the labels that each got.

#9 Update CHANGELOG and VERSION for 2.5.0 release
  CHANGELOG.md
  VERSION
Labels: lgtm, size/XS

#7 Prow job patch after migration
  prow/gcpproxy-build.sh
  prow/gcpproxy-e2e.sh
  prow/gcpproxy-presubmit.sh
  src/api_proxy/service_control/BUILD
  tests/e2e/scripts/cloud-run/deploy.sh
  tests/e2e/scripts/prow-utilities.sh
Labels: lgtm, size/S

#10 add root-level OWNERS
  OWNERS
Labels: lgtm, size/XS

#20 Add scripts/docker_make.sh
  scripts/docker_make.sh
Labels: approved, lgtm, size/M

#11 Update docs and error message with latest links
  README.md
  docker/serverless/env_start_proxy.py
Labels: approved, documentation, lgtm, size/XS

#12 Remove `-local` flag for goimports
  Makefile
Labels: approved, lgtm, size/XS

#22 Reenable backend health check
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: approved, size/S

#21 Remove gcc
  DEVELOPER.md
  Makefile
  prow/gcpproxy-build.sh
  prow/utils/prow_test_utils.sh
  scripts/all-utilities.sh
  scripts/release/release-publish.sh
  scripts/robot-release.sh
Labels: approved, lgtm, size/M

#28 Fix build-grpc-bookstore
  Makefile
  tests/endpoints/bookstore_grpc/proto/BUILD
Labels: approved, lgtm, size/S

#27 remove glide dependency in Makefile
  Makefile
Labels: approved, lgtm, size/S

#29 Deploy proxy with the runtime service account in Cloud Run e2e tests
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: approved, lgtm, size/XS

#30 Make cloud-anthos e2e test use default network
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: approved, lgtm, size/XS

#33 Support auto binding for grpc transcoding
  Makefile
  examples/grpc_dynamic_routing/envoy_config.json
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/config_manager_test.go
  tests/endpoints/bookstore_grpc/proto/api_config_auth.yaml
  tests/endpoints/bookstore_grpc/proto/api_descriptor.pb
  tests/endpoints/bookstore_grpc/proto/v1/bookstore.pb.go
  tests/endpoints/bookstore_grpc/proto/v2/bookstore_v2.pb.go
  tests/endpoints/bookstore_grpc/proto/v2/bookstore_v2.proto
  tests/endpoints/bookstore_grpc/server/server.go
  tests/env/testdata/fake_grpc_bookstore_service_config.go
  tests/integration_test/multi_grpc_services_test/multi_grpc_services_test.go
Labels: approved, lgtm, size/L

#23 b/149491061: [Refactor 2/3] Decouple TokenSubscriber platform logic from TokenInfo for IAM and IMDS
  src/envoy/token/BUILD
  src/envoy/token/iam_token_info.cc
  src/envoy/token/iam_token_info.h
  src/envoy/token/iam_token_info_test.cc
  src/envoy/token/iam_token_subscriber_fuzz_test.cc
  src/envoy/token/imds_token_info.cc
  src/envoy/token/imds_token_info.h
  src/envoy/token/imds_token_info_test.cc
  src/envoy/token/mocks.h
  src/envoy/token/sa_token_generator.cc
  src/envoy/token/sa_token_generator.h
  src/envoy/token/sa_token_generator_test.cc
  src/envoy/token/token_info.h
  src/envoy/token/token_subscriber.cc
  src/envoy/token/token_subscriber.h
  src/envoy/token/token_subscriber_factory.h
  src/envoy/token/token_subscriber_factory_impl.h
  src/envoy/token/token_subscriber_test.cc
Labels: approved, lgtm, size/XXL

#35 Delete clusters async in serverless janitor
  prow/janitor.sh
Labels: approved, lgtm, size/XS

#34 b/149491061: [Refactor 3/3] Switch over to new `TokenSubscriber` implementation
  src/envoy/http/backend_auth/BUILD
  src/envoy/http/backend_auth/config_parser.h
  src/envoy/http/backend_auth/config_parser_impl.cc
  src/envoy/http/backend_auth/config_parser_impl.h
  src/envoy/http/backend_auth/config_parser_impl_test.cc
  src/envoy/http/backend_auth/filter_config_impl.h
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/service_control_call_impl.cc
  src/envoy/http/service_control/service_control_call_impl.h
  src/envoy/token/token_subscriber_factory.h
  src/envoy/utils/BUILD
  src/envoy/utils/iam_token_subscriber.cc
  src/envoy/utils/iam_token_subscriber.h
  src/envoy/utils/iam_token_subscriber_fuzz_test.cc
  src/envoy/utils/iam_token_subscriber_test.cc
  src/envoy/utils/imds_token_subscriber.cc
  src/envoy/utils/imds_token_subscriber.h
  src/envoy/utils/imds_token_subscriber_test.cc
  src/envoy/utils/mocks.h
  src/envoy/utils/sa_token_generator.cc
  src/envoy/utils/sa_token_generator.h
  src/envoy/utils/sa_token_generator_test.cc
  src/envoy/utils/token_subscriber_factory.h
  src/envoy/utils/token_subscriber_factory_impl.h
Labels: approved, lgtm, size/XXL
