Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2020-04, with the labels that each got.

#103 b/152972988: update the cluster version for anthos test
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: approved, lgtm, size/S

#102 support websocket
  -
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  go.mod
  go.sum
  src/go/bootstrap/static/testdata/path_matcher/envoy_config.json
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/testdata/fake_data_for_dynamic_routing.go
  tests/endpoints/echo/client/client.go
  tests/endpoints/echo/server/app.go
  tests/env/components/ports.go
  tests/env/testdata/fake_echo_service_config.go
  tests/integration_test/websocket_test.go
Labels: approved, lgtm, size/L

#104 fix jwtLocation unit test flakiness
  .gitignore
  src/go/configinfo/service_info_test.go
Labels: approved, lgtm, size/S

#105 support generate_self_signed_certificate
  docker/generic/start_proxy.py
  src/go/configinfo/service_info_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/M

#108 doc/comment fix
  tests/endpoints/bookstore_grpc/proto/v2/bookstore_v2.proto
Labels: ok-to-test, size/XS

#109 b/153198370: Add service control check and jwt authn for websocket
  tests/endpoints/echo/client/client.go
  tests/env/testdata/fake_echo_service_config.go
  tests/integration_test/websocket_test.go
Labels: approved, lgtm, size/M

#107 Align `--cloud_trace_url_override` with ESPv1
  docker/generic/start_proxy.py
  src/go/commonflags/flags.go
  tests/env/components/fake_stackdriver_server.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/S

#110 Apply retry and network_fail_open for failed server response properly
  src/envoy/http/service_control/client_cache.cc
  src/envoy/http/service_control/http_call.cc
  src/envoy/http/service_control/http_call_test.cc
  tests/env/components/ports.go
  tests/integration_test/service_control_check_network_fail_test.go
  tests/integration_test/service_control_check_server_fail_test.go
  tests/integration_test/service_control_retry_timeout_test.go
  tests/integration_test/transport_security_test.go
Labels: approved, size/L

#112 use absl::StrAppend for error message in http_call
  src/envoy/http/service_control/http_call.cc
Labels: approved, lgtm, size/XS

#113 Update version number to 2.9.0.
  VERSION
Labels: approved, lgtm, size/XS

#114 Changelog for release 2.8.0
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#116 fix release script and remove useless file
  -
  scripts/release/release-show.sh
  scripts/release/release-stable.sh
Labels: approved, lgtm, size/XS

#117 Update envoy to 2020-04-06
  WORKSPACE
  src/envoy/http/service_control/filter_fuzz_test.cc
  src/envoy/http/service_control/http_call.cc
  src/envoy/http/service_control/http_call_test.cc
  src/envoy/token/token_subscriber.cc
  src/envoy/token/token_subscriber.h
  src/envoy/token/token_subscriber_test.cc
  tests/integration_test/grpc_integration_test.go
Labels: approved, size/M

#119 Support whether allowing underscore in HTTP headers
  docker/generic/start_proxy.py
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  go.mod
  go.sum
  src/go/bootstrap/static/testdata/path_matcher/envoy_config.json
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/config_manager.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/flags/flags.go
  src/go/configmanager/main/server.go
  src/go/configmanager/testdata/fake_data_for_dynamic_routing.go
  src/go/options/configgenerator.go
  tests/env/components/ports.go
  tests/integration_test/http1_integration_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, size/L

#115 Remove dead code in `path_matcher`
  src/api_proxy/path_matcher/http_template_test.cc
  src/api_proxy/path_matcher/path_matcher.cc
  src/api_proxy/path_matcher/path_matcher.h
Labels: approved, size/L

#118 Handle duplicated `snake_names` in path matcher filter config
  api/envoy/http/path_matcher/config.proto
  examples/grpc_dynamic_routing/envoy_config.json
  src/envoy/http/path_matcher/filter_config.cc
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: approved, lgtm, security-review, size/L

#120 Update to bazel 3.0.0
  .bazelrc
  .bazelversion
Labels: approved, lgtm, size/XS

#122 Covert non-5xx sidestream errors to 500 Internal Server Error
  src/envoy/http/service_control/client_cache.cc
  tests/integration_test/service_control_check_server_fail_test.go
Labels: approved, lgtm, size/S

#123 Only pass Interupt and SIGTERM signals to GCS Runner.
  src/go/gcsrunner/main/runner.go
Labels: approved, lgtm, size/XS

#126 b/153344041: deploy proxy only once for Cloud Run(Anthos)
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: approved, lgtm, size/S

#125 Update README, adding more supported features
  README.md
Labels: approved, lgtm, size/S

#128 Simplify auth code used to generate a JWT from a service account
  src/api_proxy/auth/BUILD
  src/api_proxy/auth/auth_token.cc
  src/api_proxy/auth/auth_token.h
  src/api_proxy/auth/auth_token_fuzz_test.cc
  src/api_proxy/auth/grpc_internals.h
  src/api_proxy/auth/json_util.cc
  src/api_proxy/auth/json_util.h
  src/api_proxy/auth/json_util_test.cc
  src/envoy/token/BUILD
  src/envoy/token/sa_token_generator.cc
Labels: approved, lgtm, security-review, size/XL

#129 b/154758301: add access_log and access_log_format
  docker/generic/start_proxy.py
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  src/go/util/util.go
  tests/env/components/ports.go
  tests/env/platform/files.go
  tests/integration_test/access_log_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, size/L

#132 Enforce max path length limit
  src/api_proxy/auth/auth_token.cc
  src/envoy/http/path_matcher/filter.cc
  src/envoy/http/path_matcher/filter_test.cc
  tests/fuzz/corpus/path_matcher_filter/overflow-path.prototxt
Labels: approved, lgtm, oss-fuzz-bug-fix, security-review, size/M

#136 [Cleanup] Simplify header lookup
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/token/iam_token_info_test.cc
  src/envoy/token/imds_token_info_test.cc
  src/envoy/token/token_subscriber_test.cc
Labels: approved, lgtm, size/M

#133 b/154877853: add dns_resolver_address
  .gitignore
  Makefile
  docker/generic/start_proxy.py
  go.mod
  go.sum
  src/go/configgenerator/cluster_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  src/go/util/dns_resolver.go
  src/go/util/url_util.go
  tests/env/components/config_manager.go
  tests/env/components/dns_resolver.go
  tests/env/components/ports.go
  tests/env/env.go
  tests/integration_test/access_log_test.go
  tests/integration_test/dns_resolver_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, size/XL

#137 Token refresh logic for invalid expiry times
  src/envoy/token/BUILD
  src/envoy/token/iam_token_info_test.cc
  src/envoy/token/imds_token_info_test.cc
  src/envoy/token/token_subscriber.cc
  src/envoy/token/token_subscriber_test.cc
Labels: approved, lgtm, security-review, size/L

#142 Update version number to 2.10.0.
  VERSION
Labels: approved, lgtm, size/XS

#143 Changelog for 2.9.0
  CHANGELOG.md
Labels: approved, lgtm, size/S
