Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2020-06, with the labels that each got.

#166 b/155209585 #4: Ensure all consumer/producer errors are logged in stats
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/handler_utils_test.cc
Labels: approved, lgtm, size/S

#169 b/157743299: Migrate configs from api/v2 to api/v3
  api/VERSION
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/path_matcher/envoy_config.json
  src/go/bootstrap/admin.go
  src/go/bootstrap/admin_test.go
  src/go/bootstrap/ads/bootstrap.go
  src/go/bootstrap/ads/bootstrap_test.go
  src/go/bootstrap/node.go
  src/go/bootstrap/static/bootstrap.go
  src/go/bootstrap/static/bootstrap_test.go
  src/go/bootstrap/tracing.go
  src/go/bootstrap/tracing_test.go
  src/go/configgenerator/cluster_generator.go
  src/go/configgenerator/cluster_generator_test.go
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/config_manager.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/main/server.go
  src/go/configmanager/testdata/fake_data_for_dynamic_routing.go
  src/go/gcsrunner/transform_config.go
  src/go/gcsrunner/transform_config_test.go
  src/go/util/dns_resolver.go
  src/go/util/load_assignment.go
  src/go/util/marshal.go
  src/go/util/transport_socket.go
  src/go/util/transport_socket_test.go
Labels: approved, lgtm, size/XXL

#168 [Refactor] Enforce test failures on teardown
  tests/env/env.go
  tests/integration_test/access_log_test.go
  tests/integration_test/auth_pkey_cache_test.go
  tests/integration_test/backend_auth_disable_auth_test.go
  tests/integration_test/backend_auth_using_iam_test.go
  tests/integration_test/backend_auth_using_imds_test.go
  tests/integration_test/backend_protocol_test.go
  tests/integration_test/cors_integration_test.go
  tests/integration_test/dns_resolver_test.go
  tests/integration_test/dynamic_routing_integration_test.go
  tests/integration_test/grpc_deadline_test.go
  tests/integration_test/grpc_errors_test.go
  tests/integration_test/grpc_fallback_test.go
  tests/integration_test/grpc_integration_test.go
  tests/integration_test/grpc_interop_test.go
  tests/integration_test/grpc_ministress_test.go
  tests/integration_test/grpc_streaming_test.go
  tests/integration_test/http1_deadline_test.go
  tests/integration_test/http1_integration_test.go
  tests/integration_test/http_method_override_test.go
  tests/integration_test/iam_imds_data_path_test.go
  tests/integration_test/jwt_auth_integration_test.go
  tests/integration_test/jwt_locations_test.go
  tests/integration_test/managed_service_config_test.go
  tests/integration_test/multi_grpc_services_test.go
  tests/integration_test/opencensus_tracing_test.go
  tests/integration_test/report_gcp_attributes_test.go
  tests/integration_test/service_control_access_token_test.go
  tests/integration_test/service_control_apikey_location_test.go
  tests/integration_test/service_control_apikey_restriction_test.go
  tests/integration_test/service_control_auth_fail_test.go
  tests/integration_test/service_control_basic_test.go
  tests/integration_test/service_control_cache_test.go
  tests/integration_test/service_control_check_fail_test.go
  tests/integration_test/service_control_check_network_fail_test.go
  tests/integration_test/service_control_check_server_fail_test.go
  tests/integration_test/service_control_credential_id_test.go
  tests/integration_test/service_control_failed_request_report_test.go
  tests/integration_test/service_control_http_method_test.go
  tests/integration_test/service_control_http_path_test.go
  tests/integration_test/service_control_log_test.go
  tests/integration_test/service_control_protocol_test.go
  tests/integration_test/service_control_quota_test.go
  tests/integration_test/service_control_report_network_fail_test.go
  tests/integration_test/service_control_response_code_test.go
  tests/integration_test/service_control_retry_timeout_test.go
  tests/integration_test/service_control_skip_test.go
  tests/integration_test/statistics_test.go
  tests/integration_test/transcoding_bindings_test.go
  tests/integration_test/transcoding_errors_test.go
  tests/integration_test/transport_security_test.go
  tests/integration_test/websocket_test.go
Labels: approved, lgtm, size/L

#172 [Refactor] Remove cyclic dependency in integration tests
  tests/env/components/mock_service_control.go
  tests/env/components/mock_service_control_test.go
  tests/integration_test/cors_integration_test.go
  tests/integration_test/grpc_streaming_test.go
  tests/integration_test/opencensus_tracing_test.go
  tests/integration_test/report_gcp_attributes_test.go
  tests/integration_test/service_control_protocol_test.go
  tests/integration_test/service_control_quota_test.go
  tests/integration_test/service_control_response_code_test.go
  tests/integration_test/service_control_retry_timeout_test.go
  tests/utils/retry.go
  tests/utils/service_control_utils.go
Labels: approved, lgtm, size/L

#173 Fuzz access logger and fix fuzz failures
  WORKSPACE
  src/envoy/http/backend_routing/filter_fuzz_test.cc
  src/envoy/http/path_matcher/filter_fuzz_test.cc
  src/envoy/http/service_control/filter_fuzz_test.cc
Labels: approved, lgtm, size/S

#167 b/155209585 #5: Verify stat invariants for all integration tests
  tests/env/components/health_check_helpers.go
  tests/env/components/stats_verifier.go
  tests/env/env.go
  tests/integration_test/statistics_test.go
  tests/utils/stats_fetcher.go
Labels: approved, lgtm, size/L

#174 b/157791398,b/157743299: migrate all listeners to api/v3
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/path_matcher/envoy_config.json
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/testdata/fake_data_for_dynamic_routing.go
  src/go/util/marshal.go
Labels: approved, lgtm, size/L

#175 Additional validation and filter config cleanup for Backend Routing
  api/VERSION
  api/envoy/http/backend_routing/config.proto
  src/envoy/http/backend_routing/BUILD
  src/envoy/http/backend_routing/filter_config.h
  src/envoy/http/backend_routing/filter_config_test.cc
  src/envoy/http/backend_routing/filter_test.cc
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/util/url_util.go
  src/go/util/url_util_test.go
  tests/integration_test/statistics_test.go
Labels: approved, breaking-api-change, lgtm, security-review, size/L

#176 Fix grpc-web: move grpc-web filter in front of transcoder
  examples/grpc_dynamic_routing/envoy_config.json
  src/go/configgenerator/listener_generator.go
  src/go/configmanager/config_manager_test.go
  tests/endpoints/bookstore_grpc/proto/api_descriptor.pb
  tests/endpoints/bookstore_grpc/proto/v1/bookstore.proto
Labels: approved, lgtm, size/M

#177 Cleanup service config packing in SC Filter Config
  api/VERSION
  api/envoy/http/service_control/BUILD
  api/envoy/http/service_control/config.proto
  bazel/googleapis.bzl
  bazel/service_control.bzl
  examples/service_control/envoy_config.json
  src/api_proxy/service_control/BUILD
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/filter_fuzz_test.cc
  src/envoy/http/service_control/service_control_call_impl.cc
  src/envoy/http/service_control/testdata/envoy.yaml
  src/go/configgenerator/listener_generator.go
  src/go/configmanager/config_manager_test.go
  tests/fuzz/corpus/service_control_filter/all-metrics.prototxt
  tests/fuzz/corpus/service_control_filter/bad-check.prototxt
  tests/fuzz/corpus/service_control_filter/bad-quota.prototxt
  tests/fuzz/corpus/service_control_filter/crash-api-key-header.prototxt
  tests/fuzz/corpus/service_control_filter/crash-sa-token-generator-null-token.prototxt
  tests/fuzz/corpus/service_control_filter/sc-retries.prototxt
  tests/fuzz/corpus/service_control_filter/valid-request-complex.prototxt
  tests/fuzz/corpus/service_control_filter/valid-request.prototxt
Labels: approved, lgtm, size/XXL

#180 Update version number to 2.12.0.
  VERSION
Labels: approved, lgtm, size/XS

#181 Update CHANGELOG for 2.11.0
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#182 Cleanup / validation / tests for Backend Routing
  api/envoy/http/backend_auth/config.proto
  api/envoy/http/common/base.proto
  api/envoy/http/service_control/config.proto
  api/envoy/http/service_control/requirement.proto
  src/envoy/http/backend_auth/BUILD
  src/envoy/http/backend_auth/config_parser_impl.cc
  src/envoy/http/backend_auth/config_parser_impl_test.cc
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/service_control_call_impl.h
Labels: approved, lgtm, security-review, size/M

#183 Fix duplicate import
  src/go/configgenerator/listener_generator.go
Labels: approved, lgtm, size/XS

#187 b/157610728: update googleapis to 06042020
  bazel/googleapis.bzl
  bazel/service_control.bzl
  src/api_proxy/service_control/check_response_test.cc
  src/api_proxy/service_control/request_builder.cc
  tests/endpoints/grpc_echo/BUILD
  tests/endpoints/grpc_echo/proto/api_descriptor.pb
Labels: approved, lgtm, size/M

#188 b/152334472: Change filter names to be outside the envoy namespace
  api/VERSION
  api/envoy/http/backend_auth/config.proto
  api/envoy/http/backend_routing/config.proto
  api/envoy/http/common/base.proto
  api/envoy/http/path_matcher/config.proto
  api/envoy/http/service_control/config.proto
  api/envoy/http/service_control/requirement.proto
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/path_matcher/envoy_config.json
  src/envoy/http/backend_auth/config_parser_impl.cc
  src/envoy/http/backend_auth/config_parser_impl.h
  src/envoy/http/backend_auth/config_parser_impl_test.cc
  src/envoy/http/backend_auth/filter_config_impl.h
  src/envoy/http/backend_auth/filter_factory.cc
  src/envoy/http/backend_routing/filter.cc
  src/envoy/http/backend_routing/filter_config.h
  src/envoy/http/backend_routing/filter_config_test.cc
  src/envoy/http/backend_routing/filter_factory.cc
  src/envoy/http/backend_routing/filter_test.cc
  src/envoy/http/path_matcher/filter_config.cc
  src/envoy/http/path_matcher/filter_config.h
  src/envoy/http/path_matcher/filter_config_test.cc
  src/envoy/http/path_matcher/filter_factory.cc
  src/envoy/http/path_matcher/filter_test.cc
  src/envoy/http/service_control/client_cache.cc
  src/envoy/http/service_control/client_cache.h
  src/envoy/http/service_control/client_cache_test.cc
  src/envoy/http/service_control/config_parser.cc
  src/envoy/http/service_control/config_parser.h
  src/envoy/http/service_control/config_parser_test.cc
  src/envoy/http/service_control/filter_config.h
  src/envoy/http/service_control/filter_factory.cc
  src/envoy/http/service_control/filter_fuzz_test.cc
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/handler_utils.cc
  src/envoy/http/service_control/handler_utils.h
  src/envoy/http/service_control/handler_utils_test.cc
  src/envoy/http/service_control/http_call.cc
  src/envoy/http/service_control/http_call.h
  src/envoy/http/service_control/http_call_test.cc
  src/envoy/http/service_control/mocks.h
  src/envoy/http/service_control/service_control_call.h
  src/envoy/http/service_control/service_control_call_impl.cc
  src/envoy/http/service_control/service_control_call_impl.h
  src/envoy/utils/filter_state_utils.h
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/testdata/fake_data_for_dynamic_routing.go
  src/go/gcsrunner/transform_config_test.go
  src/go/util/marshal.go
  src/go/util/util.go
  tests/fuzz/structured_inputs/backend_routing_filter.proto
  tests/fuzz/structured_inputs/path_matcher_filter.proto
  tests/fuzz/structured_inputs/service_control_filter.proto
Labels: approved, breaking-api-change, lgtm, security-review, size/L

#190 Fix C++ unit test timeouts by increasing test size
  src/api_proxy/path_matcher/BUILD
  src/api_proxy/service_control/BUILD
  src/api_proxy/utils/BUILD
  src/envoy/http/backend_auth/BUILD
  src/envoy/http/backend_routing/BUILD
  src/envoy/http/path_matcher/BUILD
  src/envoy/http/service_control/BUILD
  src/envoy/token/BUILD
  src/envoy/utils/BUILD
Labels: approved, lgtm, size/S

#186 b/158192303: #1 fix data race in config_manager_test.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
Labels: approved, size/XXL

#191 b/157896907: More stats for Backend Auth, handle rejections properly.
  src/envoy/http/backend_auth/README.md
  src/envoy/http/backend_auth/filter.cc
  src/envoy/http/backend_auth/filter.h
  src/envoy/http/backend_auth/filter_config.h
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/http/backend_routing/README.md
Labels: approved, lgtm, size/L

#196 Backend Routing - Security review #6 fixes
  api/envoy/http/backend_routing/config.proto
  examples/README.md
  src/envoy/http/backend_routing/README.md
  src/envoy/http/backend_routing/filter.cc
  src/envoy/http/backend_routing/filter_config.h
  src/envoy/http/backend_routing/filter_config_test.cc
  src/envoy/http/backend_routing/filter_fuzz_test.cc
  src/envoy/http/backend_routing/filter_test.cc
  src/envoy/http/path_matcher/filter_fuzz_test.cc
Labels: approved, lgtm, oss-fuzz-bug-fix, security-review, size/L

#193 SC Config Path - Security review #7 fixes
  api/envoy/http/service_control/config.proto
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/service_control/request_builder_test.cc
  src/api_proxy/service_control/request_info.h
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/config_parser.h
  src/envoy/http/service_control/config_parser_test.cc
  src/envoy/http/service_control/filter_stats.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/service_control_call_impl.cc
Labels: approved, lgtm, security-review, size/L

#199 Document pass through filters, handle duplicate operation names
  src/envoy/http/backend_auth/README.md
  src/envoy/http/backend_auth/config_parser_impl.cc
  src/envoy/http/backend_auth/config_parser_impl_test.cc
  src/envoy/http/backend_auth/filter.cc
  src/envoy/http/backend_routing/README.md
  src/envoy/http/backend_routing/filter_config.h
  src/envoy/http/backend_routing/filter_config_test.cc
Labels: approved, lgtm, security-review, size/M

#198 b/148454048: Increase IMDS access token timeout to 30s
  docker/generic/start_proxy.py
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/dynamic_routing/openapi_swagger.json
  examples/dynamic_routing/service_config_generated.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  src/envoy/http/backend_auth/config_parser_impl.cc
  src/envoy/http/backend_auth/config_parser_impl_test.cc
  src/envoy/http/service_control/service_control_call_impl.cc
  src/envoy/token/iam_token_info.cc
  src/envoy/token/imds_token_info.cc
  src/envoy/token/mocks.h
  src/envoy/token/token_subscriber.cc
  src/envoy/token/token_subscriber.h
  src/envoy/token/token_subscriber_factory.h
  src/envoy/token/token_subscriber_factory_impl.h
  src/envoy/token/token_subscriber_test.cc
  src/go/commonflags/flags.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configinfo/service_info.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/options/common.go
  tests/env/components/mock_iam.go
  tests/env/components/mock_metadata.go
  tests/env/components/ports.go
  tests/env/env.go
  tests/integration_test/backend_auth_using_iam_test.go
  tests/integration_test/iam_imds_data_path_test.go
  tests/integration_test/service_control_access_token_test.go
Labels: approved, lgtm, size/L

#200 b/157610728: add consumer-type and consumer-number headers
  go.mod
  go.sum
  src/api_proxy/service_control/check_response_test.cc
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/service_control/request_info.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl.h
  tests/env/components/mock_service_control.go
  tests/env/components/mock_service_control_test.go
  tests/integration_test/generated_header_prefix_test.go
Labels: approved, lgtm, size/L

#203 Handle unknown enums properly
  api/envoy/http/backend_routing/config.proto
  tests/fuzz/corpus/backend_routing_filter/crash-bad-path-translation.prototxt
Labels: approved, lgtm, oss-fuzz-bug-fix, size/S

#201 b/158192303: #2 fix data race in rollout_id_change_fetcher_test.go
  src/go/serviceconfig/rollout_id_change_fetcher_test.go
Labels: approved, lgtm, size/XS

#204 Update envoy to 6/18
  Makefile
  WORKSPACE
  api/scripts/go_proto_gen.sh
  go.mod
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/http_call_test.cc
Labels: approved, size/S

#206 b/155218831: Send error message as JSON format in response
  Makefile
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/path_matcher/envoy_config.json
  go.mod
  go.sum
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  tests/e2e/client/apiproxy_bookstore_test.py
  tests/e2e/scripts/prow-utilities.sh
  tests/endpoints/bookstore_grpc/client/client.go
  tests/endpoints/echo/client/client.go
  tests/endpoints/grpc_echo/client-test-lib.cc
  tests/integration_test/backend_protocol_test.go
  tests/integration_test/dns_resolver_test.go
  tests/integration_test/grpc_integration_test.go
  tests/integration_test/http1_deadline_test.go
  tests/integration_test/jwt_auth_integration_test.go
  tests/integration_test/jwt_locations_test.go
  tests/integration_test/managed_service_config_test.go
  tests/integration_test/service_control_auth_fail_test.go
  tests/integration_test/service_control_check_fail_test.go
  tests/integration_test/service_control_check_network_fail_test.go
  tests/integration_test/service_control_check_server_fail_test.go
  tests/integration_test/service_control_failed_request_report_test.go
  tests/integration_test/service_control_quota_test.go
  tests/integration_test/service_control_retry_timeout_test.go
  tests/integration_test/transcoding_errors_test.go
  tests/integration_test/transport_security_test.go
  tests/utils/http.go
Labels: approved, size/XL

#207 Validate against negative timeouts
  Makefile
  api/envoy/http/common/base.proto
  tests/fuzz/corpus/service_control_filter/crash-negative-timeout.prototxt
Labels: approved, lgtm, oss-fuzz-bug-fix, size/M

#209 Update changelog for v2.12.0
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#208 Update version number to 2.13.0.
  VERSION
Labels: approved, lgtm, size/XS

#211 Add api/README.md and api/script/update_version.h
  api/README.md
  api/scripts/update_version.sh
Labels: approved, size/M

#212 Fix bug in processing HTTP response, unit tests for client cache CHECK
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/client_cache.cc
  src/envoy/http/service_control/client_cache.h
  src/envoy/http/service_control/client_cache_test.cc
  src/envoy/http/service_control/http_call.cc
  src/envoy/http/service_control/http_call.h
  src/envoy/http/service_control/http_call_test.cc
  src/envoy/http/service_control/mocks.h
Labels: approved, bug, lgtm, security-review, size/L
