Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2020-09, with the labels that each got.

#306 Validate sc filter config has SC uri
  api/envoy/v8/http/service_control/config.proto
  tests/fuzz/corpus/service_control_filter/crash-missing-sc-uri.prototxt
Labels: approved, lgtm, oss-fuzz-bug-fix, size/M

#303 Improve API Regression test
  prow/gcpproxy-api-regression.sh
Labels: approved, lgtm, size/S

#305 b/166158386 #3: Add ApiKeyState into report log entry
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/service_control/request_builder_test.cc
  src/api_proxy/service_control/request_info.h
  src/api_proxy/service_control/testdata/report_request.golden
  src/api_proxy/service_control/testdata/report_request_by_consumer.golden
  src/api_proxy/service_control/testdata/report_request_empty_optional.golden
  src/api_proxy/service_control/testdata/report_request_failed.golden
  src/api_proxy/service_control/testdata/report_request_failed_bad_api_key.golden
  tests/integration_test/cors_integration_test.go
  tests/integration_test/dynamic_routing_integration_test.go
  tests/integration_test/grpc_fallback_test.go
  tests/integration_test/grpc_streaming_test.go
  tests/integration_test/http_method_override_test.go
  tests/integration_test/multi_grpc_services_test.go
  tests/integration_test/service_control_auth_fail_test.go
  tests/integration_test/service_control_basic_test.go
  tests/integration_test/service_control_cache_test.go
  tests/integration_test/service_control_check_fail_test.go
  tests/integration_test/service_control_check_network_fail_test.go
  tests/integration_test/service_control_credential_id_test.go
  tests/integration_test/service_control_failed_request_report_test.go
  tests/integration_test/service_control_http_method_test.go
  tests/integration_test/service_control_http_path_test.go
  tests/integration_test/service_control_log_test.go
  tests/integration_test/service_control_quota_test.go
  tests/integration_test/service_control_response_code_test.go
  tests/integration_test/websocket_test.go
  tests/utils/service_control_utils.go
  tests/utils/service_control_utils_test.go
Labels: approved, enhancement, lgtm, size/L

#307 Add default location in Report call for non_gcp
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/service_control/testdata/report_request_empty_optional.golden
  tests/integration_test/report_gcp_attributes_test.go
Labels: approved, size/S

#308 Support GCP deployment with service account key
  docker/generic/start_proxy.py
  src/go/configmanager/config_manager.go
  tests/e2e/scripts/gke/deploy.sh
  tests/env/components/mock_metadata.go
  tests/env/components/ports.go
  tests/integration_test/non_gcp_test.go
  tests/integration_test/service_control_access_token_test.go
  tests/integration_test/service_control_check_fail_test.go
  tests/start_proxy/start_proxy_test.py
  tests/utils/service_account.go
Labels: approved, bug, lgtm, size/L

#309 Fix incorrect sleep time for serverless service activation
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: approved, lgtm, size/XS

#310 Add test for report of gcp attributes on non-GCP
  src/go/tokengenerator/token_generator.go
  tests/env/components/ports.go
  tests/integration_test/report_gcp_attributes_test.go
Labels: approved, lgtm, size/L

#311 b/167400401: Set API version in autogenerated CORS methods
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  tests/integration_test/cors_integration_test.go
Labels: approved, lgtm, size/M

#312 Update version number to 2.18.0.
  VERSION
Labels: approved, lgtm, size/XS

#313 Update changelog for 2.17.0
  CHANGELOG.md
Labels: approved, lgtm, size/S

#314 b/167455579: For Cloud Run, report location with region instead of zone
  api/envoy/v8/http/service_control/config.proto
  src/api_proxy/service_control/request_builder_test.cc
  src/go/metadata/metadata_fetcher.go
  src/go/metadata/metadata_fetcher_test.go
  src/go/util/util.go
  tests/integration_test/report_gcp_attributes_test.go
Labels: approved, bug, lgtm, size/M

#252 Switch e2e tests to test tracing with W3C trace context propagation
  Makefile
  tests/e2e/scripts/cloud-run/deploy.sh
  tests/e2e/scripts/gke/deploy.sh
  tests/e2e/testdata/bookstore/gke/http-bookstore.yaml.template
  tests/endpoints/bookstore/http_bookstore.js
  tests/endpoints/bookstore/package-lock.json
  tests/endpoints/bookstore/package.json
Labels: approved, lgtm, size/XL

#315 b/167430314: Update envoy to 2020-09-02
  .bazelrc
  Makefile
  WORKSPACE
  docker/Dockerfile-prow-env
  envoy_build_config/extensions_build_config.bzl
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/http/service_control/filter_fuzz_test.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/http_call_test.cc
  tests/endpoints/grpc_echo/BUILD
  tests/endpoints/grpc_echo/client-test-lib.cc
  tests/endpoints/grpc_echo/grpc-test-client.cc
  tests/integration_test/access_log_test.go
Labels: approved, size/M

#318 Fix reading the remote client IP when deploying ESPv2 on Cloud Run
  docker/generic/start_proxy.py
  docker/serverless/env_start_proxy.py
  tests/e2e/scripts/cloud-run/deploy.sh
  tests/e2e/scripts/linux-test-kb-long-run.sh
  tests/start_proxy/env_start_proxy_test.py
  tests/start_proxy/start_proxy_test.py
Labels: approved, enhancement, lgtm, size/M

#320 Update deprecated API fields
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/path_matcher/envoy_config.json
  src/go/bootstrap/ads/bootstrap.go
  src/go/bootstrap/ads/bootstrap_test.go
  src/go/bootstrap/layer_runtime.go
  src/go/bootstrap/static/bootstrap.go
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/util/regex.go
  src/go/util/regex_test.go
  src/go/util/util.go
Labels: approved, lgtm, size/XL

#323 Support IP in backend address
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/util/url_util_test.go
Labels: approved, lgtm, size/L

#324 Fix broken anthos e2e test
  tests/e2e/client/apiproxy_bookstore_key_restriction_test.py
  tests/e2e/scripts/cloud-run/deploy.sh
  tests/e2e/scripts/linux-test-kb-long-run.sh
  tests/e2e/testdata/bookstore/key_restriction_test.json.template
Labels: approved, lgtm, size/M

#316 Rich access logging of http request information
  bazel/googleapis.bzl
  go.mod
  go.sum
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/service_control/request_info.h
  src/api_proxy/service_control/testdata/report_request.golden
  src/api_proxy/service_control/testdata/report_request_by_consumer.golden
  src/api_proxy/service_control/testdata/report_request_empty_optional.golden
  src/api_proxy/service_control/testdata/report_request_failed.golden
  src/api_proxy/service_control/testdata/report_request_failed_bad_api_key.golden
  tests/endpoints/grpc_echo/BUILD
  tests/utils/service_control_utils.go
  tests/utils/service_control_utils_test.go
Labels: approved, enhancement, size/L

#319 Add decoration to the route names for dynamic routing
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/path_matcher/envoy_config.json
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/util/util.go
  tests/env/components/ports.go
  tests/integration_test/opencensus_tracing_test.go
Labels: approved, size/L

#326 Revert "b/167430314: Update envoy to 2020-09-02"
  .bazelrc
  Makefile
  WORKSPACE
  docker/Dockerfile-prow-env
  envoy_build_config/extensions_build_config.bzl
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/http/service_control/filter_fuzz_test.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/http_call_test.cc
  tests/endpoints/grpc_echo/BUILD
  tests/endpoints/grpc_echo/client-test-lib.cc
  tests/endpoints/grpc_echo/grpc-test-client.cc
  tests/integration_test/access_log_test.go
Labels: approved, lgtm, size/M

#327 Fix flakes with serverless e2e tests
  tests/e2e/client/utils.py
Labels: approved, lgtm, size/S

#325 b/168120858: Split specifying root certs for backend vs sidestream SSL clients
  docker/generic/start_proxy.py
  src/go/configgenerator/cluster_generator.go
  src/go/configmanager/config_manager.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  tests/env/components/config_manager.go
  tests/env/env.go
  tests/integration_test/dynamic_routing_integration_test.go
  tests/integration_test/transport_security_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, bug, lgtm, size/L

#329 Removed un-used segmentNames in samples envoy config
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  src/go/bootstrap/static/bootstrap_test.go
Labels: approved, lgtm, size/L

#330 b/167586109: Add name prefix for backend/jwtProvider cluster
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/path_matcher/envoy_config.json
  go.mod
  src/go/configgenerator/cluster_generator.go
  src/go/configgenerator/cluster_generator_test.go
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/util/util.go
  src/go/util/xds_name.go
  src/go/util/xds_name_test.go
  tests/integration_test/opencensus_tracing_test.go
Labels: approved, size/XL

#322 b/145520483: Update example with support for dynamic routing of unconfigured requests
  examples/testdata/path_matcher/envoy_config.json
  examples/testdata/path_matcher/openapi_swagger.json
  examples/testdata/path_matcher/service_config_generated.json
Labels: approved, lgtm, size/L

#331 Update version number to 2.19.0.
  VERSION
Labels: approved, lgtm, size/XS

#333 Update CHANGELOG for 2.18.0 release
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#332 Cleanup autogeneted CORS method names
  examples/testdata/path_matcher/envoy_config.json
  go.mod
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  tests/integration_test/cors_integration_test.go
Labels: approved, enhancement, size/L

#328 add grpc_metadata_scrubber filter
  api/envoy/v8/http/grpc_metadata_scrubber/BUILD
  api/envoy/v8/http/grpc_metadata_scrubber/config.proto
  src/envoy/BUILD
  src/envoy/http/grpc_metadata_scrubber/BUILD
  src/envoy/http/grpc_metadata_scrubber/README.md
  src/envoy/http/grpc_metadata_scrubber/filter.cc
  src/envoy/http/grpc_metadata_scrubber/filter.h
  src/envoy/http/grpc_metadata_scrubber/filter_config.h
  src/envoy/http/grpc_metadata_scrubber/filter_factory.cc
  src/envoy/http/grpc_metadata_scrubber/filter_test.cc
Labels: approved, lgtm, size/L

#334 b/119265126: Remove unnecessary extensions from Envoy build
  envoy_build_config/extensions_build_config.bzl
  src/envoy/http/service_control/handler_impl_test.cc
Labels: approved, lgtm, size/L

#335 b/145520483: Fix Envoy route ordering for wildcard dynamic routing
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/path_matcher/envoy_config.json
  src/go/configgenerator/listener_generator_test.go
  src/go/configinfo/service_info.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  tests/env/env.go
  tests/env/testdata/fake_echo_service_config_for_dynamic_routing.go
  tests/env/testdata/service_config_for_fixed_dynamic_routing.json
  tests/integration_test/dynamic_routing_integration_test.go
Labels: approved, bug, lgtm, size/L

#337 Enable race/msan for go build/test
  Makefile
  src/go/serviceconfig/rollout_id_change_fetcher_test.go
Labels: approved, lgtm, size/M

#336 Enable gRPC when downstream is HTTP/1.1
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/path_matcher/envoy_config.json
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/flags/flags.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/options/configgenerator.go
  src/go/util/xds_name.go
  tests/endpoints/grpc_echo/proto/api_descriptor.pb
Labels: approved, size/L

#339 Fix quota test
  tests/e2e/client/apiproxy_bookstore_quota_test.py
Labels: approved, lgtm, size/S

#343 b/160645642: use inline headers
  src/envoy/http/backend_auth/filter.cc
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_utils.cc
  src/envoy/http/service_control/handler_utils.h
  src/envoy/http/service_control/handler_utils_test.cc
  src/envoy/http/service_control/http_call.cc
  src/envoy/utils/http_header_utils.h
Labels: approved, lgtm, size/M

#344 Add flag `--connection_buffer_limit_bytes`
  docker/generic/start_proxy.py
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  tests/env/platform/ports.go
  tests/integration_test/grpc_integration_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, enhancement, lgtm, size/L

#348 Deprecated flag --service_control_network_fail_open
  docker/generic/start_proxy.py
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/M

#350 b/169095072: fix path matcher misleading error message
  src/envoy/http/path_matcher/filter.cc
  src/envoy/http/path_matcher/filter_test.cc
  tests/integration_test/access_log_test.go
  tests/integration_test/service_control_failed_request_report_test.go
Labels: approved, lgtm, size/M

#355 Update version number to 2.20.0.
  VERSION
Labels: approved, lgtm, size/XS

#357 Update changelog for 2.19.0
  CHANGELOG.md
Labels: approved, lgtm, size/XS
