Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2020-10, with the labels that each got.

#354 Envoy route config for sidecar with x-google-backend
  examples/testdata/README.md
  examples/testdata/sidecar_backend/envoy_config.json
  examples/testdata/sidecar_backend/openapi_swagger.json
  examples/testdata/sidecar_backend/service_config_generated.json
  src/go/bootstrap/static/bootstrap_test.go
  tests/env/platform/files.go
Labels: approved, size/XXL

#362 Add proto files into grpc examples
  examples/grpc_dynamic_routing/api_descriptor.pb
  examples/grpc_dynamic_routing/grpc-test.proto
Labels: approved, lgtm, size/L

#361 Fix api regression test
  Makefile
  prow/gcpproxy-api-regression.sh
  scripts/all-utilities.sh
  scripts/robot-release.sh
Labels: approved, lgtm, size/M

#358 b/170162456: Enable route config for local backend in sidecar mode
  examples/auth/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  src/go/bootstrap/static/bootstrap_test.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  tests/integration_test/opencensus_tracing_test.go
Labels: approved, enhancement, lgtm, size/XXL

#364 b/168231721: Support BackendRule deadline configuration in sidecar mode
  examples/testdata/sidecar_backend/envoy_config.json
  src/go/configgenerator/cluster_generator.go
  src/go/configgenerator/cluster_generator_test.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  tests/env/env.go
  tests/env/platform/ports.go
  tests/env/testdata/fake_echo_service_config.go
  tests/integration_test/http1_deadline_test.go
Labels: approved, enhancement, lgtm, size/L

#349 b/162392946: #1 add response code detail in service control report
  src/api_proxy/service_control/BUILD
  src/api_proxy/service_control/check_response_convert_utils.cc
  src/api_proxy/service_control/check_response_convert_utils.h
  src/api_proxy/service_control/check_response_convert_utils_test.cc
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/service_control/request_builder.h
  src/api_proxy/service_control/request_builder_test.cc
  src/api_proxy/service_control/request_info.h
  src/api_proxy/service_control/testdata/report_request.golden
  src/api_proxy/service_control/testdata/report_request_by_consumer.golden
  src/api_proxy/service_control/testdata/report_request_failed.golden
  src/api_proxy/service_control/testdata/report_request_failed_bad_api_key.golden
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/client_cache.cc
  src/envoy/http/service_control/client_cache_test.cc
  src/envoy/http/service_control/filter.cc
  src/envoy/http/service_control/filter.h
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/mocks.h
  src/envoy/http/service_control/service_control_callback_func.h
  tests/integration_test/dynamic_routing_integration_test.go
  tests/integration_test/service_control_auth_fail_test.go
  tests/integration_test/service_control_basic_test.go
  tests/integration_test/service_control_check_fail_test.go
  tests/integration_test/service_control_check_network_fail_test.go
  tests/integration_test/service_control_failed_request_report_test.go
  tests/integration_test/service_control_quota_test.go
  tests/integration_test/service_control_response_code_test.go
  tests/utils/service_control_utils.go
  tests/utils/service_control_utils_test.go
Labels: approved, size/XXL

#366 b/162392946: #2 normalize rc details in the rest filters.
  src/envoy/http/backend_auth/BUILD
  src/envoy/http/backend_auth/filter.cc
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/http/backend_routing/BUILD
  src/envoy/http/backend_routing/filter.cc
  src/envoy/http/backend_routing/filter_test.cc
  src/envoy/http/path_matcher/BUILD
  src/envoy/http/path_matcher/filter.cc
  src/envoy/http/path_matcher/filter.h
  src/envoy/http/path_matcher/filter_test.cc
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/utils/BUILD
  src/envoy/utils/rc_detail_utils.cc
  src/envoy/utils/rc_detail_utils.h
  src/envoy/utils/rc_detail_utils_test.cc
  tests/integration_test/service_control_failed_request_report_test.go
Labels: approved, lgtm, size/L

#367 Automatically disable backend auth on non-GCP platforms
  src/go/configgenerator/cluster_generator.go
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  tests/env/components/mock_metadata.go
  tests/env/platform/ports.go
  tests/integration_test/non_gcp_test.go
Labels: approved, enhancement, lgtm, size/L

#370 b/170259809: Support for complicated http_template in envoy route match
  src/go/util/url_util.go
  src/go/util/url_util_test.go
  tests/env/testdata/fake_echo_service_config_for_dynamic_routing.go
  tests/integration_test/dynamic_routing_integration_test.go
Labels: approved, enhancement, size/L

#371 b/170423927: replace snakeName with jsonName in urlTemplate during config time
  examples/testdata/path_matcher/envoy_config.json
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/util/url_util.go
  src/go/util/url_util_test.go
Labels: approved, lgtm, size/L

#368 Use per-route config for ServiceControl filter
  api/envoy/v9/http/service_control/config.proto
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/path_matcher/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/config_parser.h
  src/envoy/http/service_control/filter.cc
  src/envoy/http/service_control/filter_factory.cc
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/handler_impl_test.cc
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/util/marshal.go
  tests/env/components/stats_verifier.go
  tests/env/testdata/fake_echo_service_config.go
  tests/integration_test/managed_service_config_test.go
Labels: approved, lgtm, size/XL

#373 Fix anthos e2e test due to failed ip allocation
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: approved, lgtm, size/XS

#374 Add bazel remote cache to api regression test
  prow/gcpproxy-api-regression.sh
Labels: approved, lgtm, size/XS

#377 b/170691898: fix path extraction for auto-gen cors methods
  examples/testdata/path_matcher/envoy_config.json
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  tests/endpoints/echo/server/app.go
  tests/integration_test/dynamic_routing_integration_test.go
Labels: approved, lgtm, size/L

#375 b/170679093: Update envoy to v1.16.0
  .bazelrc
  DEVELOPER.md
  Makefile
  WORKSPACE
  docker/Dockerfile-prow-env
  envoy_build_config/extensions_build_config.bzl
  prow/gcpproxy-api-regression.sh
  src/envoy/http/backend_auth/config_parser_impl.cc
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/http/service_control/filter_config.h
  src/envoy/http/service_control/filter_fuzz_test.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/http_call.cc
  src/envoy/http/service_control/http_call_test.cc
  src/envoy/http/service_control/service_control_call_impl.cc
  src/envoy/token/iam_token_info.cc
  src/envoy/token/token_subscriber_test.cc
  tests/endpoints/grpc_echo/BUILD
  tests/endpoints/grpc_echo/client-test-lib.cc
  tests/endpoints/grpc_echo/grpc-test-client.cc
  tests/fuzz/README.md
  tests/integration_test/access_log_test.go
  tests/integration_test/grpc_integration_test.go
  tests/integration_test/websocket_test.go
Labels: approved, size/L

#378 b/170723966: Add option to disable OpenID Connect Discovery
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  tests/integration_test/jwt_auth_integration_test.go
Labels: approved, enhancement, lgtm, size/M

#382 Update DEVELOPER.md to install `lld-10`
  DEVELOPER.md
Labels: approved, lgtm, size/XS

#381 b/170679093: Format with `clang-format-10`
  api/envoy/v9/http/grpc_metadata_scrubber/config.proto
  src/api_proxy/path_matcher/http_template.cc
  src/api_proxy/path_matcher/http_template_fuzz_test.cc
  src/api_proxy/path_matcher/http_template_test.cc
  src/api_proxy/path_matcher/path_matcher_node.cc
  src/api_proxy/service_control/logs_metrics_loader.cc
  src/api_proxy/service_control/logs_metrics_loader_test.cc
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/service_control/request_builder.h
  src/api_proxy/service_control/request_builder_test.cc
  src/api_proxy/service_control/request_info.h
  src/envoy/http/backend_auth/config_parser_impl.cc
  src/envoy/http/backend_auth/config_parser_impl_test.cc
  src/envoy/http/backend_routing/filter_fuzz_test.cc
  src/envoy/http/grpc_metadata_scrubber/filter.cc
  src/envoy/http/grpc_metadata_scrubber/filter.h
  src/envoy/http/grpc_metadata_scrubber/filter_factory.cc
  src/envoy/http/grpc_metadata_scrubber/filter_test.cc
  src/envoy/http/path_matcher/filter.cc
  src/envoy/http/path_matcher/filter.h
  src/envoy/http/path_matcher/filter_config.cc
  src/envoy/http/path_matcher/filter_config_test.cc
  src/envoy/http/path_matcher/filter_factory.cc
  src/envoy/http/path_matcher/filter_fuzz_test.cc
  src/envoy/http/path_matcher/filter_test.cc
  src/envoy/http/service_control/client_cache.cc
  src/envoy/http/service_control/client_cache_test.cc
  src/envoy/http/service_control/config_parser.h
  src/envoy/http/service_control/config_parser_test.cc
  src/envoy/http/service_control/filter.cc
  src/envoy/http/service_control/filter.h
  src/envoy/http/service_control/filter_factory.cc
  src/envoy/http/service_control/filter_fuzz_test.cc
  src/envoy/http/service_control/filter_stats.cc
  src/envoy/http/service_control/filter_stats_test.cc
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/handler_utils.cc
  src/envoy/http/service_control/http_call_test.cc
  src/envoy/http/service_control/service_control_callback_func.h
  src/envoy/token/iam_token_info_fuzz_test.cc
  src/envoy/token/imds_token_info.cc
  src/envoy/token/imds_token_info_fuzz_test.cc
  src/envoy/token/token_subscriber.cc
  src/envoy/token/token_subscriber_test.cc
  src/envoy/utils/http_header_utils.cc
  src/envoy/utils/http_header_utils_test.cc
  src/envoy/utils/json_struct.cc
  src/envoy/utils/json_struct_fuzz_test.cc
  src/envoy/utils/rc_detail_utils.cc
  src/envoy/utils/rc_detail_utils.h
Labels: approved, lgtm, size/L

#379 b/170765129: Add flags to specify `cipher_suites` for TLS certificate
  docker/generic/start_proxy.py
  src/go/configgenerator/cluster_generator.go
  src/go/configgenerator/cluster_generator_test.go
  src/go/configgenerator/listener_generator.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  src/go/util/transport_socket.go
  src/go/util/transport_socket_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, enhancement, lgtm, size/L

#376 [WIP] Change backend_auth to use per-route config
  api/envoy/v9/http/backend_auth/config.proto
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/testdata/path_matcher/envoy_config.json
  src/envoy/http/backend_auth/README.md
  src/envoy/http/backend_auth/config_parser.h
  src/envoy/http/backend_auth/config_parser_impl.cc
  src/envoy/http/backend_auth/config_parser_impl.h
  src/envoy/http/backend_auth/config_parser_impl_test.cc
  src/envoy/http/backend_auth/filter.cc
  src/envoy/http/backend_auth/filter_config.h
  src/envoy/http/backend_auth/filter_factory.cc
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/http/backend_auth/mocks.h
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/util/marshal.go
Labels: approved, size/XL

#383 Fix serverless janitor not cleaning up Cloud Functions
  prow/janitor.sh
Labels: approved, bug, lgtm, size/XS

#380 Add path_rewrite filter config and config_parser
  api/envoy/v9/http/path_rewrite/BUILD
  api/envoy/v9/http/path_rewrite/config.proto
  src/envoy/http/path_rewrite/BUILD
  src/envoy/http/path_rewrite/config_parser.h
  src/envoy/http/path_rewrite/config_parser_impl.cc
  src/envoy/http/path_rewrite/config_parser_impl.h
  src/envoy/http/path_rewrite/config_parser_impl_test.cc
Labels: approved, size/XL

#385 b/170497119: ordering route match#1 add uriTemplate
  src/go/util/httppattern/uri_template.go
  src/go/util/httppattern/uri_template_test.go
  src/go/util/httptest_util.go
Labels: approved, lgtm, size/XXL

#386 b/171074292: Switch ads to unix domain socket
  src/go/bootstrap/ads/bootstrap.go
  src/go/bootstrap/ads/bootstrap_test.go
  src/go/bootstrap/ads/flags/flags.go
  src/go/commonflags/flags.go
  src/go/configmanager/main/server.go
  src/go/options/adsbootstrapper.go
  src/go/options/common.go
  src/go/util/load_assignment.go
  tests/env/components/config_manager.go
  tests/env/components/envoy.go
  tests/env/components/health_check_helpers.go
  tests/env/env.go
  tests/env/platform/ports.go
Labels: approved, enhancement, lgtm, size/L

#388 Change configmgr to replace backend_routing with path_rewrite filter
  api/scripts/go_proto_gen.sh
  examples/dynamic_routing/envoy_config.json
  examples/testdata/path_matcher/envoy_config.json
  src/envoy/http/path_rewrite/BUILD
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/util/marshal.go
  src/go/util/xds_name.go
  tests/integration_test/statistics_test.go
  tests/utils/stats_fetcher.go
Labels: approved, size/XXL

#391 remove backend_routing envoy filter
  api/envoy/v9/http/backend_routing/BUILD
  api/envoy/v9/http/backend_routing/config.proto
  examples/README.md
  src/envoy/BUILD
  src/envoy/http/backend_routing/BUILD
  src/envoy/http/backend_routing/README.md
  src/envoy/http/backend_routing/filter.cc
  src/envoy/http/backend_routing/filter.h
  src/envoy/http/backend_routing/filter_config.h
  src/envoy/http/backend_routing/filter_config_test.cc
  src/envoy/http/backend_routing/filter_factory.cc
  src/envoy/http/backend_routing/filter_fuzz_test.cc
  src/envoy/http/backend_routing/filter_test.cc
  src/envoy/utils/rc_detail_utils.h
  tests/fuzz/structured_inputs/BUILD
  tests/fuzz/structured_inputs/backend_routing_filter.proto
Labels: approved, lgtm, size/XXL

#392 b/170497119: ordering route match#3 sort route match
  examples/grpc_dynamic_routing/envoy_config.json
  examples/testdata/path_matcher/envoy_config.json
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/util/httppattern/sort.go
  src/go/util/httppattern/sort_impl.go
  src/go/util/httppattern/sort_test.go
  tests/env/testdata/fake_echo_service_config_for_dynamic_routing.go
  tests/integration_test/dynamic_routing_integration_test.go
Labels: approved, size/XXL

#393 b/170423927: #3 replace snakeName with jsonName using syntax parsing
  examples/testdata/path_matcher/envoy_config.json
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/util/httppattern/sort_impl.go
  src/go/util/httppattern/uri_template.go
  src/go/util/httppattern/uri_template_parser.go
  src/go/util/httppattern/uri_template_parser_test.go
  src/go/util/httppattern/uri_template_test.go
  src/go/util/httppattern/util.go
  src/go/util/httppattern/util_test.go
Labels: approved, lgtm, size/XXL

#394 b/171745015: Use syntax parsing to generate route match instead of regex
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/util/httppattern/sort.go
  src/go/util/httppattern/sort_impl.go
  src/go/util/httppattern/sort_test.go
  src/go/util/httppattern/uri_template.go
  src/go/util/httppattern/uri_template_parser.go
  src/go/util/httppattern/uri_template_parser_test.go
  src/go/util/httppattern/uri_template_test.go
  src/go/util/httppattern/util.go
  src/go/util/httppattern/util_test.go
Labels: approved, size/XXL

#398 b/171924804:[Clean up] use error instead of nil to denote ParseUriTemplate failure
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/util/httppattern/sort_test.go
  src/go/util/httppattern/uri_template_parser.go
  src/go/util/httppattern/uri_template_parser_test.go
  src/go/util/httppattern/uri_template_test.go
Labels: approved, lgtm, size/L

#395 b/171326338: Add extra validation to filter config
  api/envoy/v9/http/backend_auth/config.proto
  api/envoy/v9/http/common/base.proto
  api/envoy/v9/http/path_rewrite/config.proto
  api/envoy/v9/http/service_control/requirement.proto
Labels: approved, enhancement, lgtm, size/M

#399 Remove white space in rc details
  src/envoy/http/path_rewrite/filter.cc
  src/envoy/http/path_rewrite/filter_test.cc
  src/envoy/http/service_control/filter_test.cc
Labels: approved, lgtm, size/S
