Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2020-12, with the labels that each got.

#425 b/173810289: fix request header size
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/handler_impl_test.cc
Labels: approved, lgtm, size/M

#426 Update version number to 2.22.0.
  VERSION
Labels: approved, lgtm, size/XS

#427 Update changelog for 2.21.0
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#429 Update changelog for 2.21.0
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#432 Update DEVELOPER.md
  DEVELOPER.md
Labels: approved, lgtm, size/M

#435 b/174609312 #1: Handle trailing backslash for regex-match paths
  examples/testdata/route_match/envoy_config.json
  src/envoy/BUILD
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/util/httppattern/uri_template.go
  src/go/util/httppattern/uri_template_test.go
  src/go/util/httppattern/util.go
  tests/endpoints/echo/server/app.go
  tests/env/testdata/fake_echo_service_config_for_dynamic_routing.go
  tests/integration_test/dynamic_routing_integration_test.go
Labels: approved, enhancement, lgtm, size/L

#436 b/174860114: backend retry config options
  docker/generic/start_proxy.py
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/route_match/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/flags/flags.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/options/configgenerator.go
  tests/endpoints/echo/server/app.go
  tests/env/components/echo_http_server.go
  tests/env/env.go
  tests/env/platform/ports.go
  tests/integration_test/backend_retry_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/XXL

#440 b/174609312 #2: Handle trailing slashes for exact match paths
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/util/httppattern/sort_test.go
  src/go/util/httppattern/uri_template.go
  src/go/util/httppattern/uri_template_test.go
  tests/integration_test/dynamic_routing_integration_test.go
Labels: approved, enhancement, lgtm, size/XXL

#439 b/175352046: Enable fallback to x-cloud-trace-context by default
  docker/generic/start_proxy.py
  src/go/commonflags/flags.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/options/common.go
  src/go/tracing/tracing_test.go
  tests/integration_test/opencensus_tracing_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, enhancement, lgtm, size/L

#442 Update CHANGELOG for 2.22.0
  CHANGELOG.md
Labels: approved, size/XS

#441 Update version number to 2.23.0.
  VERSION
Labels: approved, lgtm, size/XS

#443 Update CHANGELOG for 2.22.0
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#447 b/176165002: Align behavior of `X-Forwarded-Authorization` and `X-Endpoint-API-UserInfo` headers
  src/envoy/http/backend_auth/filter.cc
  src/envoy/http/backend_auth/filter_test.cc
  tests/integration_test/backend_auth_disable_auth_test.go
  tests/integration_test/jwt_auth_integration_test.go
Labels: approved, bug, lgtm, size/M

#448 b/176248192: Remove warning with empty requestTypeName
  src/go/configinfo/service_info.go
Labels: approved, lgtm, size/XS

#446 b/173024112: #1 move the NOT_FOUND rejection logic to router
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/route_match/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  src/envoy/http/backend_auth/README.md
  src/envoy/http/backend_auth/filter.cc
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/http/path_rewrite/README.md
  src/envoy/http/path_rewrite/filter.cc
  src/envoy/http/path_rewrite/filter_test.cc
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/filter.cc
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl_test.cc
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  tests/integration_test/access_log_test.go
  tests/integration_test/opencensus_tracing_test.go
  tests/integration_test/service_control_failed_request_report_test.go
Labels: approved, lgtm, size/XL

#450 b/172826703: Ensure service-config related errors are actionable
  src/go/configgenerator/cluster_generator.go
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/config_manager.go
  src/go/util/url_util.go
  src/go/util/url_util_test.go
Labels: approved, enhancement, size/L
