Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2020-11, with the labels that each got.

#401 Update envoy to per-route jwt_authn
  WORKSPACE
  src/envoy/http/backend_auth/config_parser_impl.cc
  src/envoy/http/backend_auth/config_parser_impl.h
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/http/service_control/handler_utils.cc
  src/envoy/http/service_control/handler_utils_test.cc
  src/envoy/http/service_control/http_call_test.cc
  src/envoy/http/service_control/service_control_call_impl.cc
  src/envoy/http/service_control/service_control_call_impl.h
  src/envoy/token/iam_token_info_test.cc
  src/envoy/token/imds_token_info_test.cc
  src/envoy/utils/http_header_utils.cc
  src/envoy/utils/http_header_utils_test.cc
  src/envoy/utils/json_struct_test.cc
  tests/integration_test/dynamic_routing_integration_test.go
  tests/integration_test/service_control_access_token_test.go
  tests/integration_test/service_control_auth_fail_test.go
  tests/integration_test/service_control_failed_request_report_test.go
Labels: approved, size/L

#402 b/171326666 #1: Add config generator option to allow startup on errors
  api/envoy/v9/http/backend_auth/config.proto
  api/envoy/v9/http/common/base.proto
  api/envoy/v9/http/service_control/config.proto
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/path_matcher/envoy_config.json
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/flags/flags.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/options/configgenerator.go
Labels: approved, enhancement, lgtm, size/L

#403 ConfigMgr changes: Jwt_authn use per-route config, remove path_matcher
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/route_match/envoy_config.json
  examples/testdata/route_match/openapi_swagger.json
  examples/testdata/route_match/service_config_generated.json
  examples/testdata/sidecar_backend/envoy_config.json
  go.mod
  go.sum
  src/go/bootstrap/static/bootstrap_test.go
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/configmanager/config_manager.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/util/marshal.go
  src/go/util/xds_name.go
  tests/endpoints/grpc_echo/proto/api_descriptor.pb
  tests/env/platform/files.go
  tests/integration_test/service_control_failed_request_report_test.go
  tests/integration_test/statistics_test.go
  tests/utils/stats_fetcher.go
Labels: approved, lgtm, size/XXL

#404 Fix order-dependent test output
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
Labels: approved, lgtm, size/XS

#405 remove path-matcher filter
  api/envoy/v9/http/common/base.proto
  api/envoy/v9/http/path_matcher/BUILD
  api/envoy/v9/http/path_matcher/config.proto
  api/scripts/go_proto_gen.sh
  src/envoy/BUILD
  src/envoy/http/backend_auth/README.md
  src/envoy/http/path_matcher/BUILD
  src/envoy/http/path_matcher/README.md
  src/envoy/http/path_matcher/filter.cc
  src/envoy/http/path_matcher/filter.h
  src/envoy/http/path_matcher/filter_config.cc
  src/envoy/http/path_matcher/filter_config.h
  src/envoy/http/path_matcher/filter_config_test.cc
  src/envoy/http/path_matcher/filter_factory.cc
  src/envoy/http/path_matcher/filter_fuzz_test.cc
  src/envoy/http/path_matcher/filter_test.cc
  src/envoy/http/service_control/README.md
  src/envoy/http/service_control/filter_fuzz_test.cc
  src/envoy/utils/filter_state_utils.h
  src/envoy/utils/rc_detail_utils.h
  tests/fuzz/corpus/BUILD
  tests/fuzz/corpus/path_matcher_filter/invalid-missing-headers.prototxt
  tests/fuzz/corpus/path_matcher_filter/overflow-path.prototxt
  tests/fuzz/corpus/path_matcher_filter/valid-extract-path-params.prototxt
  tests/fuzz/corpus/path_matcher_filter/valid-method-override.prototxt
  tests/fuzz/corpus/path_matcher_filter/valid-simple.prototxt
  tests/fuzz/structured_inputs/BUILD
  tests/fuzz/structured_inputs/path_matcher_filter.proto
Labels: approved, lgtm, size/XXL

#408 Update version number to 2.21.0
  VERSION
Labels: approved, lgtm, size/XS

#409 Update CHANGELOG for 2.20.0
  CHANGELOG.md
Labels: approved, lgtm, size/S

#410 Remove beta in our doc
  README.md
  docker/serverless/env_start_proxy.py
Labels: approved, lgtm, size/S

#406 b/171326666 #2: Envoy changes to use DependencyErrorBehavior in TokenSubscriber
  src/envoy/http/backend_auth/config_parser_impl.cc
  src/envoy/http/backend_auth/config_parser_impl_test.cc
  src/envoy/http/service_control/service_control_call_impl.cc
  src/envoy/token/BUILD
  src/envoy/token/mocks.h
  src/envoy/token/token_subscriber.cc
  src/envoy/token/token_subscriber.h
  src/envoy/token/token_subscriber_factory.h
  src/envoy/token/token_subscriber_factory_impl.h
  src/envoy/token/token_subscriber_test.cc
  tests/integration_test/backend_auth_using_imds_test.go
  tests/integration_test/iam_imds_data_path_test.go
Labels: approved, enhancement, size/L

#415 b/172671425: work around tsan false alarm on atomic race
  Makefile
Labels: approved, lgtm, size/XS

#414 b/172866817: Fix timing issue causing ASan test to fail
  tests/integration_test/backend_auth_using_imds_test.go
  tests/integration_test/iam_imds_data_path_test.go
Labels: approved, lgtm, size/S

#416 b/172831233: Enable traceparent trace context propagation by default
  docker/generic/start_proxy.py
  tests/e2e/scripts/cloud-run/deploy.sh
  tests/e2e/scripts/gke/deploy.sh
  tests/endpoints/echo/server/app.go
  tests/env/platform/ports.go
  tests/env/testdata/fake_echo_service_config_for_dynamic_routing.go
  tests/integration_test/generated_header_prefix_test.go
  tests/integration_test/opencensus_tracing_test.go
  tests/start_proxy/start_proxy_test.py
  tests/utils/http.go
Labels: approved, enhancement, lgtm, size/L

#418 Fix transcoding_options_test
  tests/endpoints/bookstore_grpc/proto/api_descriptor.pb
  tests/endpoints/bookstore_grpc/proto/v1/bookstore.proto
  tests/integration_test/transcoding_options_test.go
Labels: approved, lgtm, size/S

#419 Support AuthenticationRule.allow_without_credential
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  tests/env/platform/ports.go
  tests/integration_test/jwt_auth_integration_test.go
Labels: approved, lgtm, size/L

#420 Update envoy to jwt clock_skew change
  WORKSPACE
  src/envoy/http/backend_auth/config_parser_impl.cc
  src/envoy/http/service_control/service_control_call_impl.cc
  src/envoy/http/service_control/service_control_call_impl.h
  tests/integration_test/jwt_auth_integration_test.go
Labels: approved, size/M

#422 Feature: Build from Bazel
  src/envoy/BUILD
Labels: approved, lgtm, ok-to-test, size/M
