Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2020-08, with the labels that each got.

#249 b/162452414: Fix tracing sample rate
  docker/generic/start_proxy.py
  src/go/bootstrap/ads/bootstrap.go
  src/go/bootstrap/ads/bootstrap_test.go
  src/go/bootstrap/static/bootstrap.go
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/tracing/tracing.go
  src/go/tracing/tracing_test.go
  src/go/util/marshal.go
  tests/e2e/scripts/cloud-run/deploy.sh
  tests/e2e/scripts/gke/deploy.sh
  tests/env/components/envoy.go
  tests/env/components/fake_stackdriver_server.go
  tests/env/components/ports.go
  tests/env/env.go
  tests/integration_test/opencensus_tracing_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, bug, lgtm, size/XL

#257 Add logic to delete temporary directory in gcloud_build_image
  docker/serverless/gcloud_build_image
Labels: approved, lgtm, ok-to-test, size/XS

#255 Deduplicate semantically equivalent paths generated by `allowCors`
  src/go/configgenerator/route_generator.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/util/url_util.go
  src/go/util/url_util_test.go
  tests/env/components/ports.go
  tests/integration_test/cors_integration_test.go
Labels: approved, bug, lgtm, size/L

#260 Remove port replacement from GCS Runner
  src/go/gcsrunner/fetch_config.go
  src/go/gcsrunner/main/runner.go
  src/go/gcsrunner/transform_config.go
  src/go/gcsrunner/transform_config_test.go
Labels: approved, lgtm, size/L

#256 b/161479450: verify transcoding Any type
  tests/endpoints/bookstore_grpc/client/client.go
  tests/endpoints/bookstore_grpc/proto/api_descriptor.pb
  tests/endpoints/bookstore_grpc/proto/v1/bookstore.pb.go
  tests/endpoints/bookstore_grpc/proto/v1/bookstore.proto
  tests/endpoints/bookstore_grpc/proto/v2/bookstore_v2.pb.go
  tests/endpoints/bookstore_grpc/server/server.go
  tests/integration_test/transcoding_bindings_test.go
  tests/integration_test/transcoding_options_test.go
Labels: approved, lgtm, size/XL

#263 For local backend address, use HTTP as default schema
  docker/generic/start_proxy.py
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/L

#264 b/163118657: Remove transformation logic from GCS Runner.
  src/go/gcsrunner/fetch_config.go
  src/go/gcsrunner/main/runner.go
  src/go/gcsrunner/transform_config.go
  src/go/gcsrunner/transform_config_test.go
  tests/endpoints/bookstore_grpc/proto/v1/bookstore.pb.go
  tests/endpoints/bookstore_grpc/proto/v2/bookstore_v2.pb.go
Labels: approved, lgtm, size/L

#266 b/163128449: add e2e quota test on http bookstore
  tests/e2e/client/apiproxy_bookstore_quota_test.py
  tests/e2e/scripts/linux-test-kb-long-run.sh
  tests/endpoints/bookstore/bookstore_swagger_template.json
Labels: approved, size/L

#251 b/148306474,b/156410254: move generating access token by service account credential to configmanager
  api/envoy/v7/http/common/base.proto
  api/envoy/v7/http/service_control/config.proto
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  go.mod
  go.sum
  prow/gcpproxy-e2e.sh
  scripts/all-utilities.sh
  src/envoy/http/backend_auth/config_parser_impl.cc
  src/envoy/http/backend_auth/config_parser_impl_test.cc
  src/envoy/http/service_control/client_cache.cc
  src/envoy/http/service_control/service_control_call_impl.cc
  src/envoy/http/service_control/service_control_call_impl.h
  src/go/bootstrap/ads/flags/flags.go
  src/go/commonflags/flags.go
  src/go/configgenerator/cluster_generator.go
  src/go/configgenerator/cluster_generator_test.go
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/config_manager.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/flags/flags.go
  src/go/configmanager/main/server.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/metadata/metadata_fetcher.go
  src/go/metadata/metadata_fetcher_test.go
  src/go/options/adsbootstrapper.go
  src/go/options/common.go
  src/go/options/configgenerator.go
  src/go/tokengenerator/token_generator.go
  src/go/tokengenerator/token_generator_test.go
  src/go/tracing/tracing_test.go
  src/go/util/httptest_util.go
  src/go/util/token_generator_test.go
  src/go/util/url_util.go
  src/go/util/util.go
  tests/e2e/scripts/cloud-run/deploy.sh
  tests/e2e/scripts/gke/deploy.sh
  tests/e2e/scripts/prow-utilities.sh
  tests/e2e/testdata/bookstore/gke/http-bookstore.yaml.template
  tests/env/components/mock_metadata.go
  tests/env/components/mock_metadata_test.go
  tests/env/components/ports.go
  tests/env/platform/files.go
  tests/integration_test/backend_auth_disable_auth_test.go
  tests/integration_test/backend_auth_using_iam_test.go
  tests/integration_test/backend_auth_using_imds_test.go
  tests/integration_test/jwt_auth_integration_test.go
  tests/integration_test/report_gcp_attributes_test.go
  tests/integration_test/service_control_access_token_test.go
  tests/integration_test/service_control_check_fail_test.go
  tests/utils/http.go
Labels: approved, lgtm, size/XL

#267 b/156410254: cleanup unused sa-gen token related code
  src/api_proxy/auth/BUILD
  src/api_proxy/auth/auth_token.cc
  src/api_proxy/auth/auth_token.h
  src/api_proxy/auth/auth_token_fuzz_test.cc
  src/api_proxy/auth/grpc_internals.h
  src/envoy/http/service_control/service_control_call_impl.cc
  src/envoy/token/BUILD
  src/envoy/token/mocks.h
  src/envoy/token/sa_token_generator.cc
  src/envoy/token/sa_token_generator.h
  src/envoy/token/sa_token_generator_test.cc
  src/envoy/token/token_subscriber_factory.h
  src/envoy/token/token_subscriber_factory_impl.h
Labels: approved, lgtm, size/L

#268 Update changelog for v2.15.0
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#269 Update version number to 2.16.0.
  VERSION
Labels: approved, lgtm, size/XS

#270 gcloud_build_image: cd back to original directory
  docker/serverless/gcloud_build_image
  prow/e2e-gcloud-build-image.sh
Labels: approved, lgtm, size/XS

#272 Pin anthos cluster version to the latest
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: approved, lgtm, size/XS

#259 Verify trace invariants in integration tests
  Makefile
  tests/env/components/fake_stackdriver_server.go
  tests/env/env.go
  tests/integration_test/opencensus_tracing_test.go
Labels: approved, lgtm, size/M

#275 Add allowCors to a static bootstrap test
  examples/testdata/path_matcher/envoy_config.json
  examples/testdata/path_matcher/openapi_swagger.json
  examples/testdata/path_matcher/service_config_generated.json
Labels: approved, lgtm, size/M

#277 Update esp-v2-on-k8s.md
  doc/esp-v2-on-k8s.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#271 Improve quota e2e test
  tests/e2e/client/apiproxy_bookstore_quota_test.py
  tests/e2e/client/utils.py
  tests/e2e/testdata/bookstore/gke/http-bookstore.yaml.template
Labels: approved, lgtm, size/M

#278 b/164477080: Add retry mechanism on callgoogleapis when it comes into 429
  src/go/configmanager/config_manager_test.go
  src/go/serviceconfig/rollout_id_change_detector.go
  src/go/serviceconfig/rollout_id_change_fetcher_test.go
  src/go/serviceconfig/service_config_fetcher.go
  src/go/serviceconfig/service_config_fetcher_test.go
  src/go/util/request.go
  src/go/util/request_test.go
  tests/env/components/mock_service_management.go
  tests/env/components/ports.go
  tests/integration_test/managed_service_config_test.go
Labels: approved, lgtm, size/L

#281 Add more port restrictions for usability
  docker/generic/start_proxy.py
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/M

#285 Update version number to 2.17.0
  VERSION
Labels: approved, lgtm, size/XS

#286 Update CHANGELOG to 2.16.0
  CHANGELOG.md
Labels: approved, size/XS

#279 E2E test with ESPv2 TLS Termination
  tests/e2e/client/apiproxy_bookstore_key_restriction_test.py
  tests/e2e/client/utils.py
  tests/e2e/scripts/gke/deploy.sh
  tests/e2e/testdata/bookstore/gke/http-bookstore.yaml.template
Labels: approved, lgtm, size/M

#287 b/165086608: Use dedicated SA Key for JWT e2e tests
  examples/grpc_dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/grpc-test.yaml
  examples/grpc_dynamic_routing/service_config_generated.json
  tests/e2e/scripts/gen-auth-token.sh
  tests/endpoints/bookstore/bookstore_swagger_template.json
  tests/endpoints/grpc_echo/grpc-test-dynamic-routing.tmpl.yaml
  tests/endpoints/grpc_echo/grpc-test.yaml
Labels: approved, lgtm, size/S

#283 b/156286299: GCS Runner: Enable statsd with --service-cluster and --service-node flags
  src/go/gcsrunner/start_envoy.go
Labels: approved, lgtm, size/XS

#288 Update README.md and use cases
  README.md
  doc/use-cases.md
Labels: approved, documentation, lgtm, size/M

#273 Managed service rollout during e2e load test
  tests/e2e/scripts/gke/deploy.sh
Labels: approved, lgtm, size/M

#294 Give e2e test script executable permission
  prow/e2e-tight_http_bookstore_managed_using_sa_cred_long_run.sh
Labels: approved, lgtm, size/XS

#297 Update e2e deployment yaml files for latest stable k8s
  tests/e2e/testdata/bookstore_grpc/gke/bookstore.yaml
  tests/e2e/testdata/grpc_echo/gke/grpc-echo.yaml.template
  tests/e2e/testdata/grpc_interop/gke/grpc-interop.yaml.template
Labels: approved, lgtm, size/S

#293 b/166168739: Reduce noise of Envoy logs with `--enable_debug`
  docker/generic/start_proxy.py
  tests/start_proxy/start_proxy_test.py
Labels: approved, enhancement, size/XS

#296 Remove unused metrics from logs_metrics proto
  tests/env/testdata/logs_metrics.pb.txt
  tests/integration_test/dynamic_routing_integration_test.go
  tests/integration_test/grpc_fallback_test.go
  tests/integration_test/grpc_streaming_test.go
  tests/integration_test/multi_grpc_services_test.go
  tests/integration_test/service_control_auth_fail_test.go
  tests/integration_test/service_control_basic_test.go
  tests/integration_test/service_control_check_fail_test.go
  tests/integration_test/service_control_credential_id_test.go
  tests/integration_test/service_control_failed_request_report_test.go
  tests/integration_test/service_control_log_test.go
  tests/integration_test/service_control_quota_test.go
  tests/integration_test/service_control_response_code_test.go
  tests/utils/service_control_utils.go
  tests/utils/service_control_utils_test.go
Labels: approved, size/XL

#299 Remove grpc_stats filter
  examples/grpc_dynamic_routing/envoy_config.json
  src/go/configgenerator/listener_generator.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/util/util.go
Labels: approved, lgtm, size/M

#298 b/166158386 #2: Prepare integration test framework for conditional api key validation
  tests/integration_test/cors_integration_test.go
  tests/integration_test/dynamic_routing_integration_test.go
  tests/integration_test/grpc_streaming_test.go
  tests/integration_test/http_method_override_test.go
  tests/integration_test/multi_grpc_services_test.go
  tests/integration_test/service_control_auth_fail_test.go
  tests/integration_test/service_control_basic_test.go
  tests/integration_test/service_control_cache_test.go
  tests/integration_test/service_control_check_fail_test.go
  tests/integration_test/service_control_failed_request_report_test.go
  tests/integration_test/service_control_http_method_test.go
  tests/integration_test/service_control_log_test.go
  tests/integration_test/service_control_quota_test.go
  tests/integration_test/websocket_test.go
  tests/utils/service_control_utils.go
  tests/utils/service_control_utils_test.go
Labels: approved, size/XXL

#292 Add API regression presubmit test
  Makefile
  prow/gcpproxy-api-regression.sh
  scripts/all-utilities.sh
  scripts/robot-release.sh
Labels: approved, lgtm, size/M

#300 Remove streaming metrics in envoy
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/service_control/request_builder_test.cc
  src/api_proxy/service_control/request_info.h
  src/api_proxy/service_control/testdata/final_report_request.golden
  src/api_proxy/service_control/testdata/first_report_request.golden
  src/api_proxy/service_control/testdata/intermediate_report_request.golden
  src/api_proxy/service_control/testdata/report_request.golden
  src/api_proxy/service_control/testdata/report_request_by_consumer.golden
  src/api_proxy/service_control/testdata/report_request_failed.golden
  src/envoy/http/service_control/BUILD
  src/envoy/http/service_control/filter.cc
  src/envoy/http/service_control/filter.h
  src/envoy/http/service_control/filter_factory.cc
  src/envoy/http/service_control/filter_fuzz_test.cc
  src/envoy/http/service_control/filter_fuzz_test.cc:
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/mocks.h
Labels: approved, lgtm, size/XXL

#301 Add 1m sleep time for GAP backend ready
  scripts/all-utilities.sh
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: approved, lgtm, size/S

#295 b/166158386 #1: Fix error with reporting invalid API Keys
  src/api_proxy/service_control/BUILD
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/service_control/request_builder_test.cc
  src/api_proxy/service_control/request_info.h
  src/api_proxy/service_control/testdata/report_request_failed_bad_api_key.golden
  src/envoy/http/service_control/client_cache.cc
  src/envoy/http/service_control/client_cache_test.cc
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl_test.cc
  tests/integration_test/cors_integration_test.go
  tests/integration_test/service_control_auth_fail_test.go
  tests/integration_test/service_control_basic_test.go
  tests/integration_test/service_control_check_fail_test.go
  tests/integration_test/service_control_check_network_fail_test.go
  tests/integration_test/service_control_credential_id_test.go
  tests/integration_test/service_control_failed_request_report_test.go
  tests/integration_test/service_control_quota_test.go
  tests/utils/service_control_utils.go
Labels: approved, bug, enhancement, lgtm, size/XXL

#302 b/166496629: Better naming of healthz and cors operations
  examples/testdata/path_matcher/envoy_config.json
  src/go/configgenerator/listener_generator_test.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/util/util.go
  tests/integration_test/cors_integration_test.go
Labels: approved, enhancement, lgtm, size/M
