Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2021-01, with the labels that each got.

#452 Upgrade golang to latest stable(1.15.6)
  Makefile
  docker/Dockerfile-prow-env
  go.mod
  go.sum
  src/go/util/url_util.go
  src/go/util/url_util_test.go
  tests/env/platform/ports.go
  tests/env/testdata/cert.conf
  tests/env/testdata/client.crt
  tests/env/testdata/client.key
  tests/env/testdata/server.crt
  tests/env/testdata/server.key
  tests/integration_test/client_cancellation_test.go
  tests/integration_test/transport_security_test.go
Labels: approved, lgtm, size/L

#451 b/173024112: #2 add 405 directResponse in router
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/route_match/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/util/util.go
  src/go/util/util_test.go
  tests/integration_test/http_method_override_test.go
  tests/integration_test/service_control_failed_request_report_test.go
Labels: approved, lgtm, size/XXL

#453 b/176829461: Export envoy stats at end of sidecar e2e tests
  scripts/all-utilities.sh
  tests/e2e/scripts/linux-grpc-test-long-run.sh
  tests/e2e/scripts/linux-test-kb-long-run.sh
  tests/e2e/scripts/prow-utilities.sh
  tests/e2e/scripts/test-grpc-interop.sh
Labels: approved, lgtm, size/M

#456 b/176433373: Normalize service configs in integration tests
  tests/env/env.go
  tests/env/testdata/fake_echo_service_config.go
  tests/env/testdata/fake_echo_service_config_for_dynamic_routing.go
  tests/env/testdata/fake_grpc_bookstore_service_config.go
  tests/integration_test/cors_integration_test.go
  tests/integration_test/grpc_fallback_test.go
  tests/integration_test/http_method_override_test.go
  tests/integration_test/service_control_basic_test.go
  tests/integration_test/service_control_check_fail_test.go
  tests/integration_test/service_control_http_method_test.go
  tests/integration_test/service_control_http_path_test.go
  tests/integration_test/service_control_log_test.go
  tests/integration_test/service_control_response_code_test.go
  tests/integration_test/transport_security_test.go
Labels: approved, lgtm, size/L

#454 b/176433373: Cleanup usages of `getOrCreateMethod`
  go.mod
  src/go/configgenerator/cluster_generator_test.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator_test.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
Labels: approved, enhancement, lgtm, size/XL

#457 b/176912395: Automatically configure stream idle timeouts
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/grpc-test.yaml
  examples/grpc_dynamic_routing/service_config_generated.json
  examples/service_control/envoy_config.json
  examples/testdata/route_match/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/flags/flags.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/options/configgenerator.go
  src/go/util/time.go
  src/go/util/util.go
  tests/integration_test/grpc_deadline_test.go
  tests/integration_test/http1_deadline_test.go
Labels: approved, enhancement, lgtm, size/XL

#459 b/177252401: Add integration test for bug in transcoding
  tests/env/platform/ports.go
  tests/integration_test/transcoding_errors_test.go
Labels: approved, bug, lgtm, size/M

#460 Changelog for v2.23.0
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#461 Update version number to 2.24.0.
  VERSION
Labels: approved, lgtm, size/XS

#445 Update Envoy to v1.17.0
  .bazelrc
  .bazelversion
  Makefile
  WORKSPACE
  bazel/bazel_rules_python.bzl
  prow/.bazelrc
  prow/gcpproxy-presubmit.sh
  scripts/setup-clang-asan.sh
  src/envoy/http/service_control/filter_fuzz_test.cc
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/http_call.cc
  src/envoy/http/service_control/http_call_test.cc
  src/envoy/token/token_subscriber.cc
  src/envoy/token/token_subscriber_test.cc
Labels: approved, lgtm, size/L

#463 b/176538814: Propagate trace ID to correlate access logs and traces
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/service_control/request_builder_test.cc
  src/api_proxy/service_control/request_info.h
  src/api_proxy/service_control/testdata/report_request.golden
  src/envoy/http/service_control/filter.cc
  src/envoy/http/service_control/filter_test.cc
  src/envoy/http/service_control/handler.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/handler_utils.cc
  src/envoy/http/service_control/mocks.h
  tests/integration_test/opencensus_tracing_test.go
  tests/utils/service_control_utils.go
Labels: approved, enhancement, lgtm, size/L

#467 Add an option to gcsrunner to set Envoy application log path.
  src/go/gcsrunner/main/runner.go
  src/go/gcsrunner/start_envoy.go
Labels: approved, lgtm, size/S

#464 Allow backend address override
  docker/generic/start_proxy.py
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  tests/env/platform/ports.go
  tests/integration_test/non_gcp_test.go
  tests/integration_test/opencensus_tracing_test.go
Labels: approved, enhancement, lgtm, size/L

#468 b/178530647 #1: Respond with HTTP 400 when required headers are omitted in CORS preflight request
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/gcsrunner/main/runner.go
  src/go/gcsrunner/start_envoy.go
  tests/env/platform/ports.go
  tests/integration_test/cors_integration_test.go
  tests/utils/http.go
Labels: approved, bug, lgtm, size/L
