Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2021-12, with the labels that each got.

#639 b/208891954: disallow colon in url wildcard path segment for route match
  docker/generic/start_proxy.py
  src/go/commonflags/flags.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configinfo/service_info.go
  src/go/options/common.go
  src/go/util/dns_resolver.go
  src/go/util/httppattern/uri_template.go
  src/go/util/httppattern/uri_template_test.go
  src/go/util/httppattern/util.go
  tests/endpoints/bookstore_grpc/proto/api_descriptor.pb
  tests/endpoints/bookstore_grpc/proto/v1/bookstore.pb.go
  tests/endpoints/bookstore_grpc/proto/v1/bookstore.proto
  tests/endpoints/bookstore_grpc/proto/v2/bookstore_v2.pb.go
  tests/endpoints/bookstore_grpc/server/server.go
  tests/env/platform/ports.go
  tests/env/testdata/fake_grpc_bookstore_service_config.go
  tests/integration_test/transcoding_bindings_test/transcoding_bindings_test.go
  tests/start_proxy/start_proxy_test.py
Labels: lgtm, approved, size/XL

#642 Update help text for flag enable_strict_transport_security
  docker/generic/start_proxy.py
Labels: size/XS, lgtm, approved

#640 Support http.rules in the service config for gRPC transcoding
  Makefile
  examples/grpc_dynamic_routing/envoy_config.json
  src/go/configgenerator/filterconfig/filter_generator.go
  src/go/configgenerator/filterconfig/filter_generator_test.go
  src/go/configgenerator/filterconfig/update_proto_descriptor_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/options/configgenerator.go
  tests/endpoints/bookstore_grpc/proto/BUILD
  tests/endpoints/bookstore_grpc/proto/api_descriptor.pb
  tests/endpoints/bookstore_grpc/proto/v1/bookstore.proto
  tests/env/platform/ports.go
  tests/env/testdata/fake_grpc_bookstore_service_config.go
  tests/integration_test/cors_integration_test/cors_integration_test.go
  tests/integration_test/transcoding_bindings_test/transcoding_bindings_test.go
Labels: lgtm, size/L, approved

#643 Port cl/408418478 and cl/410078340 to github.
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
Labels: lgtm, size/M, approved

#644 Fix some typos
  src/go/configgenerator/filterconfig/filter_generator_test.go
  src/go/configgenerator/filterconfig/update_proto_descriptor_test.go
  src/go/configinfo/service_info.go
Labels: lgtm, size/S, approved

#646 Remove codes to use filePath in GrpcJsonTranscoder
  src/go/configgenerator/filterconfig/filter_generator.go
  src/go/configgenerator/filterconfig/filter_generator_test.go
  src/go/options/configgenerator.go
Labels: lgtm, size/M, approved
