Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2021-06, with the labels that each got.

#505 b/184731851: Fix overhead latency calculation for backend timeout
  src/envoy/http/service_control/handler_utils.cc
  src/envoy/http/service_control/handler_utils_test.cc
Labels: approved, bug, lgtm, size/L

#525 Update CHANGELOG for 2.27.0 release
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#526 Fix python2 in scripts/release/release-stable.sh and space in scripts/release/release-stable.sh.
  scripts/release/release-qualify.sh
  scripts/release/release-stable.sh
Labels: approved, lgtm, size/XS

#527 Add missing space in scripts/release/release-tag-git.sh
  scripts/release/release-tag-git.sh
Labels: approved, lgtm, size/XS

#534 Enable jwks async fetch by default
  docker/generic/start_proxy.py
  examples/auth/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  go.mod
  go.sum
  src/go/configgenerator/filterconfig/filter_gen_jwt_authn.go
  src/go/configgenerator/filterconfig/filter_gen_jwt_authn_test.go
  src/go/configmanager/flags/flags.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/options/configgenerator.go
  tests/env/platform/ports.go
  tests/integration_test/auth_pkey_cache_test/auth_pkey_cache_test.go
  tests/integration_test/opencensus_tracing_test/opencensus_tracing_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, size/L

#535 Add flag to enable operation name header
  docker/generic/start_proxy.py
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  src/go/util/util.go
  tests/integration_test/generated_header_prefix_test/generated_header_prefix_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, enhancement, lgtm, size/L

#537 add e2e grpc-streaming tests
  tests/e2e/client/grpc/grpc_stress_input.py
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: approved, size/S

#539 Update version number to 2.28.0.
  VERSION
Labels: approved, lgtm, size/XS

#540 Update Changelog for 2.28.0
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#541 Update release scripts for making version update before making release
  scripts/release/release-new-branch.sh
  scripts/release/release-publish.sh
Labels: approved, lgtm, size/S

#538 b/189965239: Allow using another service account for GCS fetches.
  src/go/gcsrunner/fetch_config.go
  src/go/gcsrunner/fetch_config_test.go
  src/go/gcsrunner/main/runner.go
  src/go/gcsrunner/serviceaccount.go
Labels: approved, lgtm, size/L

#546 Disable preserve downstream scheme
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/route_match/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  src/go/bootstrap/ads/bootstrap_test.go
  src/go/bootstrap/layer_runtime.go
Labels: approved, lgtm, size/M

#549 Rename a few methods visibility in configgenerator.
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
Labels: approved, lgtm, size/S

#552 Add operation name as route name for backend route.
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/route_match/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
Labels: approved, lgtm, size/XL

#555 Update version number to 2.29.0
  VERSION
Labels: approved, lgtm, size/XS

#556 Update CHANGELOG.md for 2.29.0
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#554 b/192247795: support backendRetryOnStatusCodes
  docker/generic/start_proxy.py
  src/go/configgenerator/route_generator.go
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  src/go/util/util.go
  tests/integration_test/backend_retry_test/backend_retry_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, size/L
