Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2021-05, with the labels that each got.

#507 b/185919750: upgrade to the latest 18.2
  WORKSPACE
  examples/grpc_dynamic_routing/envoy_config.json
  src/go/configgenerator/route_generator.go
  tests/integration_test/http1_deadline_test/http1_deadline_test.go
Labels: approved, lgtm, size/M

#509 b/187411694: add perTryTimeout for doing retry when the upstream times out
  docker/generic/start_proxy.py
  src/go/configgenerator/route_generator.go
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  tests/endpoints/echo/server/app.go
  tests/env/platform/ports.go
  tests/integration_test/backend_retry_test/backend_retry_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, size/L

#502 Add flag --cors_max_age to support configure Access-Control-Max-Age response header
  docker/generic/start_proxy.py
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  tests/integration_test/cors_integration_test/cors_integration_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, lgtm, ok-to-test, size/M

#511 Add path normalization options for CVE-2021-29492
  WORKSPACE
  docker/generic/start_proxy.py
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/route_match/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  go.mod
  go.sum
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/flags/flags.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/options/configgenerator.go
  tests/env/platform/ports.go
  tests/integration_test/cors_integration_test/cors_integration_test.go
  tests/integration_test/dynamic_routing_integration_test/dynamic_routing_integration_test.go
  tests/start_proxy/start_proxy_test.py
Labels: approved, enhancement, lgtm, size/XL

#512 Update version number to 2.27.0.
  VERSION
Labels: approved, lgtm, size/XS

#513 Changelog for v2.26.0
  CHANGELOG.md
Labels: approved, lgtm, size/XS

#514 GCS Runner: Allow unknown static fields
  src/go/gcsrunner/start_envoy.go
Labels: approved, lgtm, size/XS

#515 GCS Runner: Handle deadline exceeded properly
  src/go/gcsrunner/fetch_config.go
Labels: approved, lgtm, size/S

#517 Changelog for v2.26.1
  CHANGELOG.md
Labels: approved, size/XS

#516 b/188583118: Update googleapis/googleapis for golang code
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#518 Update release scripts to allow patch release
  scripts/release/release-changelog.sh
  scripts/release/release-new-branch.sh
  scripts/release/release-publish.sh
  scripts/release/release-stable.sh
  scripts/release/release-tag-git.sh
Labels: approved, lgtm, size/M

#519 b/188808823: Simplify CORS regex and fix brittle tests
  src/go/configgenerator/route_generator_test.go
  src/go/util/regex.go
  src/go/util/regex_test.go
Labels: approved, lgtm, size/S

#520 b/188906398: Reduce backoff initial latency
  src/go/gcsrunner/fetch_config.go
  src/go/gcsrunner/main/runner.go
Labels: approved, lgtm, size/S
