Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2021-09, with the labels that each got.

#592 Changelog for v2.30.2
  CHANGELOG.md
Labels: size/XS, lgtm, approved

#593 b/188654656:add jwt_pad_forward_payload_header
  docker/generic/start_proxy.py
  src/go/configgenerator/filterconfig/filter_gen_jwt_authn.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  tests/env/testdata/fake_jwt.go
  tests/integration_test/jwt_auth_integration_test/jwt_auth_integration_test.go
  tests/start_proxy/start_proxy_test.py
Labels: size/L, approved

#596 b/195940890: Log all levels to stderr in gcsrunner
  src/go/gcsrunner/main/runner.go
Labels: size/XS, lgtm, approved, needs-ok-to-test

#598 Add X-User-Agent as default cors_allow_headers
  docker/generic/start_proxy.py
  tests/start_proxy/start_proxy_test.py
Labels: size/M, approved

#601 Replace deprecated HeaderMatch_ExactMatch
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/route_match/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  go.mod
  go.sum
  src/go/configgenerator/filterconfig/filter_generator.go
  src/go/configgenerator/filterconfig/filter_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/config_manager.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  tests/integration_test/service_control_quota_test/service_control_quota_test.go
Labels: approved, size/XL

#603 Replace deprecated http2_protocol_options
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  src/go/bootstrap/ads/bootstrap.go
  src/go/bootstrap/ads/bootstrap_test.go
  src/go/configgenerator/cluster_generator.go
  src/go/configgenerator/cluster_generator_test.go
  src/go/util/load_assignment.go
  src/go/util/marshal.go
  src/go/util/xds_name.go
Labels: lgtm, size/L, approved

#604 Update version to 2.30.3
  VERSION
Labels: size/XS, lgtm, approved

#605 Update CHANGELOG for 2.30.3
  CHANGELOG.md
Labels: size/XS, approved

#606 add anypb to fix copybara
  src/go/util/load_assignment.go
Labels: size/XS, lgtm, approved

#599 b/198157523: Manually verify JWKS URI allows query param
  src/go/configgenerator/filterconfig/filter_gen_jwt_authn_test.go
  tests/env/testdata/fake_jwt.go
  tests/integration_test/jwt_auth_integration_test/jwt_auth_integration_test.go
Labels: lgtm, size/M, approved

#608 b/200210941: Update application log format
  docker/generic/start_proxy.py
  src/go/gcsrunner/start_envoy.go
  tests/start_proxy/start_proxy_test.py
Labels: enhancement, size/XS, lgtm, approved

#610 Add a registry parameter to gcloud_build_image
  docker/serverless/gcloud_build_image
Labels: lgtm, size/S, approved

#614 Add license files
  docker/Dockerfile-envoy
  docker/licenses/LICENSE
  docker/licenses/README.md
  docker/licenses/extract-licenses.sh
  go.mod
  go.sum
Labels: lgtm, approved, size/XXL

#613 Update gcloud_build_image again to support GAR
  docker/serverless/gcloud_build_image
  prow/e2e-gcloud-build-image.sh
Labels: lgtm, size/M, approved

#611 b/185372123: Use alpine as base image
  docker/Dockerfile-envoy
  docker/Dockerfile-proxy.tmpl
  docker/licenses/LICENSE
  docker/licenses/README.md
  docker/licenses/extract-licenses.sh
  docker/licenses/others/docker-alpine-glibc/LICENSE
  docker/serverless/env_start_proxy.py
Labels: lgtm, approved, size/XL
