Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2021-08, with the labels that each got.

#573 Update service_control_client_cxx with improved quota cache.
  bazel/service_control.bzl
  tests/env/components/mock_service_control.go
  tests/integration_test/service_control_quota_test/service_control_quota_test.go
Labels: approved, lgtm, size/L

#576 Update version to 2.30.0
  VERSION
Labels: approved, lgtm, size/XS

#577 Update CHANGELOG for 2.30.0
  CHANGELOG.md
Labels: approved, size/XS

#579 Fix basic CORS with default cors_allow_origin=*
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  tests/integration_test/cors_integration_test/cors_integration_test.go
Labels: lgtm, size/L, approved

#581 Updated CHANGELOG for 2.30.1
  CHANGELOG.md
Labels: size/XS, lgtm, approved

#582 Update release scripts to use python3
  scripts/release/release-qualify.sh
  scripts/release/validate_release.py
Labels: lgtm, size/M, approved

#585 Added SkipEnvoyHealthCheck to fix some flaky integration tests
  tests/env/env.go
  tests/integration_test/backend_auth_using_iam_test/backend_auth_using_iam_test.go
  tests/integration_test/backend_auth_using_imds_test/backend_auth_using_imds_test.go
  tests/integration_test/iam_imds_data_path_test/iam_imds_data_path_test.go
Labels: size/S, approved

#586 b/195940890: Improve gcsrunner remote dependency handling
  src/go/gcsrunner/fetch_config.go
  src/go/gcsrunner/fetch_config_test.go
  src/go/gcsrunner/main/runner.go
  src/go/gcsrunner/serviceaccount.go
Labels: lgtm, size/L, approved, ok-to-test

#591 Update VERSION
  VERSION
Labels: size/XS, lgtm, approved
