Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2022-03, with the labels that each got.

#667 b/221072669: Remove envoy runtime flag preserve_downstream_scheme
  docker/generic/start_proxy.py
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/route_match/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  src/go/bootstrap/ads/bootstrap_test.go
  src/go/bootstrap/layer_runtime.go
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/util/util.go
  tests/e2e/scripts/linux-grpc-test-long-run.sh
Labels: lgtm, size/L, approved

#670 Update Envoy to v1.21.1 and Bazel to v5.0.0
  .bazelversion
  WORKSPACE
  bazel/googleapis.bzl
  examples/BUILD
  tests/endpoints/grpc_interop/proto/BUILD
  tests/env/testdata/BUILD
Labels: lgtm, size/S, approved

#672 Updated release version to 2.35.0
  VERSION
Labels: size/XS, lgtm, approved

#673 Updated CHANGELOG for 2.35.0
  CHANGELOG.md
Labels: size/XS, lgtm, approved

#676 Fix service manage timeout
  tests/env/env.go
  tests/integration_test/managed_service_config_test/managed_service_config_test.go
Labels: size/S, approved

#677 Fix service_management_config integration test
  src/envoy/token/token_subscriber.cc
Labels: size/XS, lgtm, approved

#678 Revert "Fix service manage timeout (#676)"
  tests/env/env.go
  tests/integration_test/managed_service_config_test/managed_service_config_test.go
Labels: lgtm, size/S, approved

#675 Add response gzip,brotli compression
  docker/Dockerfile-prow-env
  docker/generic/start_proxy.py
  envoy_build_config/extensions_build_config.bzl
  examples/grpc_dynamic_routing/envoy_config.json
  go.mod
  go.sum
  src/go/bootstrap/static/bootstrap_test.go
  src/go/configgenerator/filterconfig/filter_gen_compressor.go
  src/go/configgenerator/filterconfig/filter_generator.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  src/go/util/marshal.go
  src/go/util/xds_name.go
  tests/endpoints/bookstore_grpc/client/client.go
  tests/env/platform/ports.go
  tests/integration_test/compression_test/compression_test.go
  tests/start_proxy/start_proxy_test.py
Labels: size/L, approved
