Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2022-06, with the labels that each got.

#698 Update DEVELOPER.md
  DEVELOPER.md
Labels: size/M, approved

#699 Update build system to use latest tooling (bazelisk, clang-13, go-18, etc.)
  .bazelrc
  DEVELOPER.md
  Makefile
  api/scripts/go_proto_gen.sh
  doc/esp-v2-on-cloudrun.md
  docker/Dockerfile-prow-env
  go.mod
  go.sum
  prow/README.md
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: size/L, approved

#700 Update janitor to clean up e2e clusters
  prow/janitor.sh
Labels: size/XS, approved

#697 Update service-control-client to 05/31/2022
  bazel/service_control.bzl
  src/api_proxy/service_control/request_builder.cc
  src/api_proxy/service_control/testdata/allocate_quota_request.golden
  src/api_proxy/service_control/testdata/allocate_quota_request_android_ios.golden
  src/api_proxy/service_control/testdata/allocate_quota_request_no_method_name.golden
  src/api_proxy/service_control/testdata/allocate_quota_request_without_api_key.golden
  src/api_proxy/service_control/testdata/allocate_quota_request_without_api_key_projectid.golden
Labels: size/S, approved

#703 Update base alpine image to 3.16
  docker/Dockerfile-envoy
Labels: size/XS, lgtm, approved

#705 b/207727749: Added two new options to flag backend_dns_lookup_family and changed its default to "v4preferred"
  docker/generic/start_proxy.py
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/route_match/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  src/go/configgenerator/cluster_generator.go
  src/go/configgenerator/cluster_generator_test.go
  src/go/configmanager/flags/flags.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/options/configgenerator.go
  tests/endpoints/echo/server/app.go
  tests/env/components/config_manager.go
  tests/env/components/dns_resolver.go
  tests/env/components/echo_http_server.go
  tests/env/env.go
  tests/env/platform/network.go
  tests/env/platform/ports.go
  tests/env/testdata/fake_echo_service_config.go
  tests/integration_test/dns_resolver_test/dns_resolver_test.go
  tests/utils/args.go
Labels: lgtm, size/L, approved, ok-to-test

#707 Update VERSION
  VERSION
Labels: size/XS, approved

#708 Update changelog for v2.37.0
  CHANGELOG.md
Labels: size/XS, lgtm, approved

#710 Ignore APIAllowlist in service info.
  src/go/configinfo/service_info.go
Labels: lgtm, size/M, approved
