Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2022-04, with the labels that each got.

#680 update outdated flag --version help text
  docker/generic/start_proxy.py
  tests/start_proxy/start_proxy_test.py
Labels: lgtm, size/L, approved

#681 update flag --service help text
  docker/generic/start_proxy.py
Labels: size/XS, lgtm, approved

#683 Fix a test-only race condition by protecting critical sections.
  src/go/serviceconfig/rollout_id_change_detector.go
  src/go/serviceconfig/rollout_id_change_fetcher_test.go
  src/go/serviceconfig/service_config_fetcher.go
  src/go/serviceconfig/service_config_fetcher_test.go
  src/go/util/request.go
Labels: lgtm, size/M, approved

#685 b/223679580: Add option to enable strict request validation in transcoder
  src/go/configgenerator/filterconfig/filter_generator.go
  src/go/configgenerator/filterconfig/filter_generator_test.go
  src/go/options/configgenerator.go
Labels: enhancement, lgtm, size/M, approved

#684 Upgrade envoy to 1.22.0
  .bazelrc
  WORKSPACE
  api/scripts/go_proto_gen.sh
  docker/Dockerfile-envoy
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/route_match/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  src/envoy/http/backend_auth/config_parser_impl.cc
  src/envoy/http/service_control/service_control_call_impl.cc
  src/envoy/token/token_subscriber.cc
  src/envoy/utils/filter_state_utils.cc
  src/go/configgenerator/filterconfig/filter_gen_backend_auth.go
  src/go/configgenerator/filterconfig/filter_gen_path_rewrite.go
  src/go/configgenerator/filterconfig/filter_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/util/marshal.go
  tests/integration_test/backend_protocol_test/backend_protocol_test.go
  tests/integration_test/backend_retry_test/backend_retry_test.go
  tests/integration_test/non_gcp_test/non_gcp_test.go
  tests/integration_test/transcoding_bindings_test/transcoding_bindings_test.go
  tests/integration_test/transcoding_errors_test/transcoding_errors_test.go
Labels: size/L, approved

#686 Updated release version to 2.36.0
  VERSION
Labels: size/XS, lgtm, approved

#687 Updated CHANGELOG for 2.36.0
  CHANGELOG.md
Labels: size/XS, lgtm, approved

#689 b/223014490: Converge default flag values
  .bazelversion
  src/go/bootstrap/ads/flags/flags.go
  src/go/commonflags/flags.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configmanager/flags/flags.go
  src/go/configmanager/flags/flags_test.go
  src/go/options/configgenerator.go
Labels: lgtm, size/L, approved
