Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2022-07, with the labels that each got.

#714 fix flaky integration tests by dynamic allocating token_agent_port
  src/go/configgenerator/filterconfig/filter_generator.go
  src/go/configgenerator/listener_generator.go
  src/go/tokengenerator/token_generator.go
  src/go/util/httppattern/sort.go
  src/go/util/httppattern/uri_template.go
  tests/endpoints/bookstore_grpc/client/client.go
  tests/endpoints/health_check/server.go
  tests/env/env.go
  tests/env/platform/ports.go
Labels: lgtm, size/M, approved

#713 Update to latest service_control_client
  bazel/service_control.bzl
Labels: size/XS, approved

#716 b/235088060: Add option to enable verbose tracing (not enabled, not exposed)
  docker/generic/start_proxy.py
  src/go/commonflags/flags.go
  src/go/options/common.go
  src/go/tracing/tracing.go
  tests/start_proxy/start_proxy_test.py
Labels: lgtm, size/M, approved

#718 Add VisibilityRule to the go Marshall
  src/go/util/marshal.go
Labels: size/XS, lgtm, approved

#715 Hard code health check to skip service control.
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/util/util.go
  tests/endpoints/bookstore_grpc/proto/BUILD
  tests/endpoints/bookstore_grpc/proto/api_descriptor.pb
  tests/endpoints/bookstore_grpc/proto/v1/bookstore.proto
  tests/env/testdata/fake_grpc_bookstore_service_config.go
  tests/integration_test/grpc_health_check_test/grpc_health_check_test.go
  tests/integration_test/service_control_skip_test/service_control_skip_test.go
Labels: lgtm, size/L, approved, ok-to-test

#719 Add dafudeng to prow OWNERs
  OWNERS
Labels: size/XS, lgtm, approved

#720 Upgrade envoy to v1.23.0.
  .gitignore
  WORKSPACE
  src/envoy/http/backend_auth/filter.cc
  src/envoy/http/backend_auth/filter_test.cc
  src/envoy/http/path_rewrite/filter.cc
  src/envoy/http/path_rewrite/filter_test.cc
  src/envoy/http/service_control/filter.cc
  src/envoy/http/service_control/handler.h
  src/envoy/http/service_control/handler_impl.cc
  src/envoy/http/service_control/handler_impl.h
  src/envoy/http/service_control/handler_impl_test.cc
  src/envoy/http/service_control/handler_utils.cc
  src/envoy/http/service_control/http_call.cc
  src/envoy/http/service_control/mocks.h
  src/envoy/token/token_subscriber.cc
  src/envoy/token/token_subscriber_test.cc
Labels: lgtm, size/L, approved

#721 Update VERSION to 2.38.0
  VERSION
Labels: size/XS, lgtm, approved

#722 Add changelog for 2.38.0
  CHANGELOG.md
Labels: size/XS, lgtm, approved

#723 Add option TranscodingRejectCollision for transcoding. Default is false.
  go.mod
  go.sum
  src/go/configgenerator/filterconfig/filter_generator.go
  src/go/options/configgenerator.go
Labels: lgtm, size/M, approved
