Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2022-02, with the labels that each got.

#658 Expose `--ads_named_pipe`
  docker/generic/start_proxy.py
  tests/start_proxy/start_proxy_test.py
Labels: enhancement, lgtm, size/S, approved

#659 b/208258342: add transcoding_match_unregistered_custom_verb
  go.mod
  go.sum
  src/go/configgenerator/filterconfig/filter_generator.go
  src/go/configmanager/config_manager.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  tests/integration_test/transcoding_bindings_test/transcoding_bindings_test.go
Labels: lgtm, size/L, approved

#660 Update version to 2.34.0
  VERSION
Labels: size/XS, lgtm, approved

#661 Update CHANGELOG for 2.34.0
  CHANGELOG.md
Labels: size/XS, lgtm, approved

#664 b/213477382: Correctly escape user-provided regex paths
  src/go/util/httppattern/uri_template.go
  src/go/util/httppattern/uri_template_test.go
Labels: bug, lgtm, size/S, approved

#665 b/213477382: Add option to allow discovery APIs
  src/go/configinfo/service_info.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
Labels: size/XS, lgtm, approved
