Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2022-10, with the labels that each got.

#737 fix build_envoy_image failure
  docker/Dockerfile-envoy
  tests/integration_test/service_control_access_token_test/service_control_access_token_test.go
Labels: size/XS, lgtm, approved

#736 b/249381233: add a flag "backend_cluster_maximum_requests:
  src/go/configgenerator/cluster_generator.go
  src/go/configgenerator/cluster_generator_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  tests/env/platform/ports.go
  tests/integration_test/backend_circuit_breaker_test/backend_circuit_breaker_test.go
Labels: size/L, approved

#738 fix a typo in the flag comment
  src/go/configmanager/flags/flags.go
Labels: size/XS, approved

#739 Fix cloud-run e2e test failure, increase sleep time before the test
  tests/e2e/scripts/cloud-run/deploy.sh
Labels: size/XS, approved

#741 Clean up orphaned firewall rules
  prow/janitor.sh
Labels: lgtm, size/S, approved

#742 Clean up orphaned forwarding rules and target proxies
  prow/janitor.sh
Labels: lgtm, size/M, approved

#744 b/254093361: fix status comparison for py2->py3
  tests/e2e/client/apiproxy_transcoding_fuzz_test.py
Labels: size/XS, lgtm, approved

#746 Update version to 2.39.0
  VERSION
Labels: size/XS, lgtm, approved

#748 Changelog for v2.39.0
  CHANGELOG.md
Labels: size/XS, approved
