Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2023-01, with the labels that each got.

#774 Bump version to 2.41.0
  VERSION
Labels: size/XS, lgtm, approved

#775 Update CHANGELOG for release 2.41.0
  CHANGELOG.md
Labels: size/XS, lgtm, approved

#777 Add HTTP backend info for each method in config generator and a test-only HTTP backend address
  .gitignore
  src/go/configgenerator/cluster_generator.go
  src/go/configgenerator/cluster_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
  src/go/options/configgenerator.go
Labels: lgtm, approved, size/XL

#780 update go version to 1.18
  go.mod
  go.sum
Labels: lgtm, size/M, approved

#779 Add flag --disable_jwt_audience_service_name_check
  docker/generic/start_proxy.py
  src/go/configgenerator/filterconfig/filter_gen_jwt_authn.go
  src/go/configgenerator/filterconfig/filter_gen_jwt_authn_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
  tests/env/platform/ports.go
  tests/integration_test/http1_integration_test/http1_integration_test.go
  tests/start_proxy/start_proxy_test.py
Labels: lgtm, size/L, approved

#781 Skip transcoder completely if test-only http backend address is set.
  src/go/configgenerator/filterconfig/filter_generator.go
  src/go/configgenerator/filterconfig/filter_generator_test.go
Labels: lgtm, size/S, approved
