Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2023-10, with the labels that each got.

#856 feat: Add transcoding_match_unregistered_custom_verb to start_proxy.py
  docker/generic/start_proxy.py
Labels: lgtm, size/S, approved, needs-ok-to-test

#857 Move reusable logic between Transcoder and GFX Filter to util
  src/go/configgenerator/filtergen/grpc_transcoder.go
  src/go/configgenerator/filtergen/util.go
  src/go/configgenerator/filtergen/util_test.go
Labels: lgtm, size/L, approved

#862 Enable mitigation for CVE 2023-09-08
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/route_match/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  src/go/bootstrap/ads/bootstrap_test.go
  src/go/bootstrap/layer_runtime.go
Labels: lgtm, size/S, approved

#863 Fix e2e error
  tests/e2e/client/apiproxy_bookstore_test.py
  tests/e2e/client/grpc/grpc_stress_input.py
Labels: size/XS, lgtm, approved

#865 Add changelog for 2.46.0
  CHANGELOG.md
Labels: size/XS, lgtm, approved
