Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2023-08, with the labels that each got.

#842 [WIP] Make health check name configurable
  src/go/configgenerator/filtergen/service_control.go
  src/go/configgenerator/filtergen/service_control_test.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
Labels: lgtm, size/S, approved

#844 refactor: generate CORS per-vHost config in CORS filter
  src/go/configgenerator/filtergen/backend_auth.go
  src/go/configgenerator/filtergen/compressor.go
  src/go/configgenerator/filtergen/cors.go
  src/go/configgenerator/filtergen/filtergen.go
  src/go/configgenerator/filtergen/grpc_metadata_scrubber.go
  src/go/configgenerator/filtergen/grpc_transcoder.go
  src/go/configgenerator/filtergen/grpc_web.go
  src/go/configgenerator/filtergen/header_sanitizer.go
  src/go/configgenerator/filtergen/health_check.go
  src/go/configgenerator/filtergen/http_connection_manager.go
  src/go/configgenerator/filtergen/jwt_authn.go
  src/go/configgenerator/filtergen/path_rewrite.go
  src/go/configgenerator/filtergen/router.go
  src/go/configgenerator/filtergen/service_control.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
Labels: size/L, approved

#847 Make health check names configurable
  src/go/bootstrap/static/bootstrap_test.go
  src/go/configgenerator/filtergen/backend_auth.go
  src/go/configgenerator/filtergen/path_rewrite.go
  src/go/configgenerator/filtergen/service_control.go
  src/go/configgenerator/filtergen/service_control_test.go
  src/go/configgenerator/filtergen/util.go
  src/go/configinfo/service_info.go
  src/go/configmanager/flags/flags.go
  src/go/options/configgenerator.go
Labels: size/M, approved

#848 refactor: implement RouteGenerator for backend routes
  src/go/configgenerator/clustergen/remote_backend.go
  src/go/configgenerator/routegen/backend.go
  src/go/configgenerator/routegen/backend_test.go
  src/go/configgenerator/routegen/cors.go
  src/go/configgenerator/routegen/health_check.go
  src/go/configgenerator/routegen/helpers/backend_route.go
  src/go/configgenerator/routegen/routegentest/routegentest.go
  src/go/configgenerator/routegen/util.go
  src/go/configgenerator/routegen/utils_test.go
  src/go/configinfo/service_info.go
Labels: lgtm, approved, size/XXL
