Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2023-03, with the labels that each got.

#787 refactor: move filter generator logic into individual files
  src/go/configgenerator/filter_generator.go
  src/go/configgenerator/filterconfig/filter_generator.go
  src/go/configgenerator/filterconfig/preserve_default_http_binding_test.go
  src/go/configgenerator/filterconfig/update_proto_descriptor_test.go
  src/go/configgenerator/filtergen/backend_auth.go
  src/go/configgenerator/filtergen/backend_auth_test.go
  src/go/configgenerator/filtergen/compressor.go
  src/go/configgenerator/filtergen/cors.go
  src/go/configgenerator/filtergen/grpc_metadata_scrubber.go
  src/go/configgenerator/filtergen/grpc_transcoder.go
  src/go/configgenerator/filtergen/grpc_transcoder_test.go
  src/go/configgenerator/filtergen/grpc_web.go
  src/go/configgenerator/filtergen/health_check.go
  src/go/configgenerator/filtergen/health_check_test.go
  src/go/configgenerator/filtergen/jwt_authn.go
  src/go/configgenerator/filtergen/jwt_authn_test.go
  src/go/configgenerator/filtergen/path_rewrite.go
  src/go/configgenerator/filtergen/router.go
  src/go/configgenerator/filtergen/service_control.go
  src/go/configgenerator/filtergen/service_control_test.go
  src/go/configgenerator/filtergen/test_lib.go
  src/go/configgenerator/filtergen/util.go
  src/go/configgenerator/listener_generator.go
Labels: lgtm, approved, size/XXL

#788 Change TestOnlyHTTPBackend to LocalHTTPBackend.
  src/go/configgenerator/filtergen/grpc_transcoder.go
  src/go/configgenerator/filtergen/grpc_transcoder_test.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configinfo/service_info.go
  src/go/options/configgenerator.go
Labels: lgtm, size/M, approved

#789 refactor: move business logic to filter generators
  src/go/configgenerator/filter_generator.go
  src/go/configgenerator/filtergen/backend_auth.go
  src/go/configgenerator/filtergen/backend_auth_test.go
  src/go/configgenerator/filtergen/compressor.go
  src/go/configgenerator/filtergen/cors.go
  src/go/configgenerator/filtergen/grpc_metadata_scrubber.go
  src/go/configgenerator/filtergen/grpc_transcoder.go
  src/go/configgenerator/filtergen/grpc_transcoder_test.go
  src/go/configgenerator/filtergen/grpc_web.go
  src/go/configgenerator/filtergen/health_check.go
  src/go/configgenerator/filtergen/health_check_test.go
  src/go/configgenerator/filtergen/jwt_authn.go
  src/go/configgenerator/filtergen/jwt_authn_test.go
  src/go/configgenerator/filtergen/path_rewrite.go
  src/go/configgenerator/filtergen/router.go
  src/go/configgenerator/filtergen/service_control.go
  src/go/configgenerator/filtergen/service_control_test.go
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configinfo/method_info.go
  src/go/configinfo/service_info.go
Labels: approved, size/XL

#792 Update a few packages in go.mod.
  go.mod
  go.sum
  tests/integration_test/grpc_integration_test/grpc_integration_test.go
  tests/integration_test/transcoding_bindings_test/transcoding_bindings_test.go
  tests/integration_test/transcoding_errors_test/transcoding_errors_test.go
  tests/integration_test/transcoding_options_test/transcoding_options_test.go
Labels: approved, size/XL

#794 Support http backend override in http backend rule. This is noop for espv2.
  package.json
  src/go/configgenerator/filtergen/grpc_transcoder.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
Labels: lgtm, size/L, approved

#795 Honor the HTTP backend rule in the backend rule instead of local backend Address.
  src/go/configgenerator/route_generator_test.go
  src/go/configinfo/service_info.go
  src/go/util/util.go
Labels: lgtm, size/M, approved

#790 debug: change integration test JWT to have a large payload
  tests/env/testdata/fake_jwt.go
  tests/integration_test/auth_pkey_cache_test/auth_pkey_cache_test.go
  tests/integration_test/grpc_integration_test/grpc_integration_test.go
  tests/integration_test/opencensus_tracing_test/opencensus_tracing_test.go
  tests/integration_test/service_control_check_fail_test/service_control_check_fail_test.go
  tests/integration_test/service_control_check_network_fail_test/service_control_check_network_fail_test.go
  tests/integration_test/service_control_quota_test/service_control_quota_test.go
  tests/integration_test/service_control_retry_timeout_test/service_control_retry_timeout_test.go
  tests/integration_test/transcoding_errors_test/transcoding_errors_test.go
  tests/integration_test/transport_security_test/transport_security_test.go
  tests/integration_test/websocket_test/websocket_test.go
Labels: lgtm, size/L, approved

#798 Reduce default jwt_cache_size to 1000
  docker/generic/start_proxy.py
  examples/auth/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  src/go/configmanager/flags/flags.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/options/configgenerator.go
Labels: size/S, approved

#799 build: update RBE cache silo ID
  DEVELOPER.md
  README.md
  scripts/all-utilities.sh
Labels: lgtm, size/M, approved

#801 move x-http-method-override to beginning of filter chain
  api/envoy/v11/http/header_sanitizer/BUILD
  api/envoy/v11/http/header_sanitizer/config.proto
  api/scripts/go_proto_gen.sh
  examples/auth/envoy_config.json
  examples/dynamic_routing/envoy_config.json
  examples/grpc_dynamic_routing/envoy_config.json
  examples/service_control/envoy_config.json
  examples/testdata/route_match/envoy_config.json
  examples/testdata/sidecar_backend/envoy_config.json
  src/envoy/BUILD
  src/envoy/http/header_sanitizer/BUILD
  src/envoy/http/header_sanitizer/filter.cc
  src/envoy/http/header_sanitizer/filter.h
  src/envoy/http/header_sanitizer/filter_factory.cc
  src/envoy/http/service_control/filter.cc
  src/go/configgenerator/filter_generator.go
  src/go/configgenerator/filtergen/header_sanitizer.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/configmanager/testdata/test_fixed_mode_dynamic_routing.go
  src/go/util/marshal.go
  src/go/util/xds_name.go
  tests/env/platform/ports.go
  tests/integration_test/http1_integration_test/http1_integration_test.go
  tests/integration_test/jwt_auth_integration_test/jwt_auth_integration_test.go
Labels: enhancement, size/L, approved

#802 Add back in HTTP method override in service control filter
  api/README.md
  src/envoy/http/service_control/filter.cc
Labels: lgtm, size/S, approved

#803 Bump version to 2.43.0
  VERSION
Labels: size/XS, lgtm, approved

#805 Add empty descriptor set in empty transcoder config.
  src/go/configgenerator/filtergen/grpc_transcoder.go
Labels: size/XS, lgtm, approved
