Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2023-04, with the labels that each got.

#806 Revert: Add back in HTTP method override in service control filter (#802)
  api/README.md
  src/envoy/http/service_control/filter.cc
Labels: lgtm, size/M, approved

#807 Change `GenFilterConfig()` to return `proto.Message` instead of `Any`
  src/go/configgenerator/filter_generator.go
  src/go/configgenerator/filtergen/backend_auth.go
  src/go/configgenerator/filtergen/backend_auth_test.go
  src/go/configgenerator/filtergen/compressor.go
  src/go/configgenerator/filtergen/cors.go
  src/go/configgenerator/filtergen/grpc_metadata_scrubber.go
  src/go/configgenerator/filtergen/grpc_transcoder.go
  src/go/configgenerator/filtergen/grpc_transcoder_test.go
  src/go/configgenerator/filtergen/grpc_web.go
  src/go/configgenerator/filtergen/header_sanitizer.go
  src/go/configgenerator/filtergen/health_check.go
  src/go/configgenerator/filtergen/health_check_test.go
  src/go/configgenerator/filtergen/jwt_authn.go
  src/go/configgenerator/filtergen/jwt_authn_test.go
  src/go/configgenerator/filtergen/path_rewrite.go
  src/go/configgenerator/filtergen/router.go
  src/go/configgenerator/filtergen/service_control.go
  src/go/configgenerator/filtergen/util.go
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/util/xds_name.go
Labels: lgtm, approved, size/XL

#809 Update Envoy to v1.25.4
  .bazelrc
  .bazelversion
  WORKSPACE
  src/envoy/http/grpc_metadata_scrubber/filter_test.cc
Labels: size/M, approved

#814 b/277969940: Upgrade config generator libraries to use golang proto v2
  src/go/bootstrap/admin_test.go
  src/go/bootstrap/ads/bootstrap.go
  src/go/bootstrap/layer_runtime.go
  src/go/bootstrap/static/bootstrap_test.go
  src/go/configgenerator/cluster_generator.go
  src/go/configgenerator/cluster_generator_test.go
  src/go/configgenerator/filter_generator.go
  src/go/configgenerator/filtergen/backend_auth.go
  src/go/configgenerator/filtergen/backend_auth_test.go
  src/go/configgenerator/filtergen/compressor.go
  src/go/configgenerator/filtergen/cors.go
  src/go/configgenerator/filtergen/grpc_metadata_scrubber.go
  src/go/configgenerator/filtergen/grpc_transcoder.go
  src/go/configgenerator/filtergen/grpc_transcoder_test.go
  src/go/configgenerator/filtergen/grpc_web.go
  src/go/configgenerator/filtergen/header_sanitizer.go
  src/go/configgenerator/filtergen/health_check.go
  src/go/configgenerator/filtergen/health_check_test.go
  src/go/configgenerator/filtergen/jwt_authn.go
  src/go/configgenerator/filtergen/jwt_authn_test.go
  src/go/configgenerator/filtergen/path_rewrite.go
  src/go/configgenerator/filtergen/router.go
  src/go/configgenerator/filtergen/service_control.go
  src/go/configgenerator/filtergen/service_control_test.go
  src/go/configgenerator/filtergen/util.go
  src/go/configgenerator/listener_generator.go
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator.go
  src/go/configgenerator/route_generator_test.go
  src/go/configinfo/service_info.go
  src/go/configinfo/service_info_test.go
  src/go/configmanager/config_manager.go
  src/go/configmanager/config_manager_test.go
  src/go/configmanager/testdata/test_fetch_listeners.go
  src/go/metadata/metadata_fetcher_test.go
  src/go/serviceconfig/rollout_id_change_fetcher_test.go
  src/go/serviceconfig/service_config_fetcher_test.go
  src/go/tracing/tracing.go
  src/go/tracing/tracing_test.go
  src/go/util/load_assignment.go
  src/go/util/marshal.go
  src/go/util/marshal_test.go
  src/go/util/request.go
  src/go/util/request_test.go
  src/go/util/transport_socket.go
  src/go/util/transport_socket_test.go
  tests/env/testdata/json_config_parser.go
Labels: lgtm, approved, size/XL

#815 b/278300246: expose --health_check_grpc_backend_no_traffic_interval
  docker/generic/start_proxy.py
  tests/start_proxy/start_proxy_test.py
Labels: lgtm, size/S, approved

#816 Refactor of cluster generators with dependency isolation
  src/go/configgenerator/clustergen/doc.go
  src/go/configgenerator/clustergen/iam.go
  src/go/configgenerator/clustergen/imds.go
  src/go/configgenerator/clustergen/jwt_authn.go
  src/go/configgenerator/clustergen/local_backend.go
  src/go/configgenerator/clustergen/local_http_backend.go
  src/go/configgenerator/clustergen/remote_backend.go
  src/go/configgenerator/clustergen/service_control.go
  src/go/configgenerator/clustergen/token_agent.go
  src/go/configgenerator/helpers/backend.go
  src/go/configgenerator/helpers/dns.go
  src/go/configgenerator/helpers/doc.go
  src/go/configgenerator/helpers/health.go
  src/go/configgenerator/helpers/tls.go
Labels: lgtm, approved, size/XL

#811 Update Changelog for v2.44
  CHANGELOG.md
Labels: size/XS, approved

#818 implement factories for a few simple cluster generators
  go.mod
  go.sum
  src/go/configgenerator/clustergen/clustergen.go
  src/go/configgenerator/clustergen/clustergen_test.go
  src/go/configgenerator/clustergen/iam.go
  src/go/configgenerator/clustergen/iam_test.go
  src/go/configgenerator/clustergen/imds.go
  src/go/configgenerator/clustergen/imds_test.go
  src/go/configgenerator/clustergen/local_http_backend.go
  src/go/configgenerator/clustergen/token_agent.go
  src/go/configgenerator/clustergen/token_agent_test.go
  src/go/configgenerator/helpers/backend.go
  src/go/configgenerator/helpers/discovery.go
  src/go/configgenerator/helpers/dns.go
  src/go/configgenerator/helpers/doc.go
  src/go/configgenerator/helpers/health.go
  src/go/configgenerator/helpers/service_control.go
  src/go/configgenerator/helpers/service_control_test.go
  src/go/configgenerator/helpers/tls.go
  src/go/configgenerator/helpers/tls_test.go
  src/go/util/transport_socket.go
Labels: lgtm, approved, size/XXL
