Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2024-03, with the labels that each got.

#884 Update googleapi version to latest
  bazel/googleapis.bzl
  tests/env/components/stats_verifier.go
Labels: size/XS, approved

#886 Update prow job to clean up unused LBs and static IPs
  prow/janitor.sh
Labels: lgtm, size/S, approved

#887 Remove not helpful log string that might get too large.
  src/go/configgenerator/routegen/proxy_backend.go
Labels: size/XS, lgtm, approved
