Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2024-07, with the labels that each got.

#915 Refactor httpRuleToHTTPPattern to public
  src/go/configgenerator/routegen/util.go
Labels: lgtm, size/S

#916 Update Go version to 1.22.5
  docker/Dockerfile-prow-env
  go.mod
  go.sum
Labels: size/L, approved

#919 Update golang.org/x/net from v0.9.0 to v0.23.0
  go.mod
  go.sum
Labels: lgtm, size/S

#920 Update the ESP version to 2.50.0
  VERSION
Labels: size/XS, lgtm

#921 Add CHANGELOG for 2.50.0
  CHANGELOG.md
Labels: size/XS, lgtm
