Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2024-01, with the labels that each got.

#872 Update the Bootstrap proto link in Envoy Filters README.md
  src/envoy/README.md
Labels: size/XS, lgtm, approved, needs-ok-to-test

#874 Update version to 2.47.0
  VERSION
Labels: size/XS

#876 Add CHANGELOG for 2.47.0
  CHANGELOG.md
Labels: size/XS

#873 Add the retry logic to the request to get metadata in MetadataFetcher.
  src/go/metadata/metadata_fetcher.go
  src/go/metadata/metadata_fetcher_test.go
Labels: size/M, approved, ok-to-test
