Repository GoogleCloudPlatform/esp-v2, pull requests merged in 2025-02, with the labels that each got.

#948 Update version to 2.52.0
  VERSION
Labels: size/XS, lgtm, approved

#949 Add CHANGELOG for 2.52.0
  CHANGELOG.md
Labels: size/XS, lgtm, approved

#950 Add the envoy version update guide in DEVELOPER.md
  DEVELOPER.md
Labels: lgtm, size/S, approved

#952 Do not configure host rewrite for http backend.
  src/go/configgenerator/listener_generator_test.go
  src/go/configgenerator/route_generator_test.go
  src/go/configgenerator/routegen/proxy_backend.go
  src/go/configgenerator/routegen/proxy_backend_test.go
Labels: size/S, approved
